import type {Preset,Sample,Point} from './index';
export const FOUNDATION:'illustro-foundation-1';
export type Curve=readonly (readonly [number,number])[];
export type Source='pressure'|'velocity'|'tilt'|'azimuth'|'twist'|'direction'|'distance'|'time'|'random';
export type Target='size'|'opacity'|'flow'|'spacing'|'rotation'|'aspect'|'scatter'|'density'|'grain'|'hue'|'saturation'|'value';
export type Mapping={source:Source;target:Target;min:number;max:number;mode:'multiply'|'add'|'replace';curve:Curve;input?:readonly [number,number];repeat?:boolean;fallback?:number};
export type Envelope={mode:'none'|'ramp'|'pressure'|'fade'|'known'|'release';unit:'distance'|'time';length:number;minimum:number;curve:Curve};
export type Texture={kind:'paper'|'hatch'|'noise'|'image';resource:string|null;strength:number;minimum:number;scale:number;sizeMode:'absolute'|'relative';space:'paper'|'tip';rotation:number;followDirection:boolean;invert:boolean;aa:boolean};
export type Resource={kind:'mask'|'texture';width:number;height:number;alpha:number[];label?:string};
export type Stabilization={scope:'brush'|'common';constant:number;fast:number;speedMode:'increase'|'reduce';post:number};
export type ForceFade={scope:'brush'|'common';enabled:boolean;start:number;end:number;minimum:number;curve:Curve};
export type FoundationPreset={format:'illustro-brush-preset';version:2;engine:typeof FOUNDATION;id:string;name:string;category:string;purpose:string;kind:string;renderer:string;size:number;opacity:number;flow:number;color:[number,number,number];blend:'normal'|'erase'|'multiply'|'screen';paint:'saturated'|'build-up';tip:{shape:string;resource:string|null;aspect:number;hardness:number;angle:number;direction:boolean;azimuth:boolean;twist:boolean};spacing:{unit:'relative'|'absolute';value:number;minimum:number;maximum:number;exposureMs:number};pressure:{deviceCurve:Curve;curve:Curve;smoothing:number;fallback:number;sizeSlope?:number};stabilization:Stabilization;forceFade:ForceFade;prediction:{enabled:boolean;source:'auto'|'browser'|'linear';horizon:number;maxDistance:number;turnCos:number};dynamics:Mapping[];limits:{size:[number,number];opacity:[number,number];flow:[number,number]};taper:Record<'size'|'opacity'|'flow'|'grain',{start:Envelope;end:Envelope}>;texture:Record<'tip'|'paper'|'stroke',Texture>;scatter:{enabled:boolean;radius:number;radiusMode:'relative'|'absolute';particleSize:number;sizeMode:'relative'|'absolute';density:number;bias:number;rotation:'tip'|'direction'|'center'};random:{target:Target|'position';amount:number}[];resources:Record<string,Resource>;extensions:Record<string,unknown>};
export type StrokeContext={deviceCurve?:Curve;commonStabilization?:Omit<Stabilization,'scope'>;commonForceFade?:Omit<ForceFade,'scope'>;knownLength?:number;knownDuration?:number};
export type CursorState={shape:string;resource:string|null;size:number;aspect:number;rotation:number;color:number[];opacity:number;barrelRoll:number|null};
export type DeepPartial<T>=T extends readonly unknown[]?T:T extends object?{[P in keyof T]?:DeepPartial<T[P]>}:T;
export function createPreset(id:string,name:string,changes?:DeepPartial<FoundationPreset>):FoundationPreset;
export function validateFoundation(preset:unknown):FoundationPreset;
export function compilePreset(preset:FoundationPreset,context?:StrokeContext):Preset;
export function evaluateDynamics(point:Point,preset:Preset,index:number,seed:readonly [number,number],distance:number,speed:number,direction:number,time:number):Record<Target,number>;
export const referenceBrushes:FoundationPreset[];
export function exportPresets(presets:FoundationPreset[]):string;
export function importPresets(json:string):FoundationPreset[];
export function cursorState(preset:FoundationPreset,sample:Sample,context?:StrokeContext):CursorState;
export function geometryContext(samples:Sample[]):StrokeContext;
export function correctGeometry(samples:Sample[],strength?:number):Sample[];
export function captureInput(event:PointerEvent,transform?:(x:number,y:number)=>[number,number],capabilities?:{tilt?:boolean;azimuth?:boolean;twist?:boolean},origin?:string):Sample[];
export function predictFoundation(points:Point[],now:number,browser:Sample[],preset:Preset):(Point&{predicted:true})|null;
export class PresetState {constructor(presets:FoundationPreset[]);saved:Map<string,FoundationPreset>;select(id:string,policy?:'restore'|'per-brush'|'shared'):FoundationPreset;override(values:DeepPartial<FoundationPreset>):FoundationPreset;current():FoundationPreset;commit():void;}
export class RendererRegistry {register(id:string,provider:{compile:(preset:FoundationPreset,context:StrokeContext)=>Preset}):()=>void;compile(preset:FoundationPreset,context:StrokeContext):Preset;}
export const rendererRegistry:RendererRegistry;
