import * as B from '@rt/baseline-shaders';
import {TILE,STRIDE,keysFor,commandBounds,LatestMailbox,continuous,solidTileCovered,liveAccumulation} from '@rt/model';
import * as S from '@rt/shaders';
// Solid ink and swept material share exact single-stroke MAX coverage.
// Restrict scheduling changes to the new Foundation, retaining legacy behavior.
const foundationUnion=p=>!!p?.__foundation&&(continuous(p)||!!p.__foundation.coverageUnion);
const emptyPreset={hardness:1,bristles:7,aspect:1,grainScale:1,grainRotation:0,tip:'round',grainKind:'paper',blend:'normal'};
const HISTORY_GPU_BUDGET=16*1024*1024,HISTORY_TILE_RESERVATION=TILE*TILE*4*2;
const glPresentVertex=`#version 300 es
void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);gl_Position=vec4(p*2.-1.,0,1);}`;
const glPresent=`#version 300 es
precision highp float;
uniform sampler2D source;out vec4 result;
void main(){vec4 s=texelFetch(source,ivec2(gl_FragCoord.xy),0);result=vec4(s.rgb+vec3(1.-s.a),1.);}`;
const wgPresent=`
@group(0)@binding(0)var source:texture_2d<f32>;
@vertex fn vertex(@builtin(vertex_index)i:u32)->@builtin(position)vec4f{
 var p=array<vec2f,3>(vec2f(-1.,-1.),vec2f(3.,-1.),vec2f(-1.,3.));
 return vec4f(p[i],0.,1.);
}
@fragment fn fragment(@builtin(position)pos:vec4f)->@location(0)vec4f{
 let size=vec2i(textureDimensions(source));
 let q=clamp(vec2i(pos.xy),vec2i(0),size-vec2i(1));
 let s=textureLoad(source,q,0);
 return vec4f(s.rgb+vec3f(1.-s.a),1.);
}`;
export function parameters(p=emptyPreset,x=0,y=0,n=0,mode=0,w=2048,h=1536,cw=1024,ch=768,same=false,liveBlend=0,bandSectors=64){const out=new Float32Array([x,y,n,mode,p.hardness,p.bristles,p.dualAspect??p.aspect,p.grainScale,Math.cos(p.grainRotation),Math.sin(p.grainRotation),S.kinds[p.tip],p.dual?S.kinds[p.dual]:-1,S.grainKinds[p.grainKind],S.blends[p.blend],p.__foundation?.coverageUnion?2:p.__foundation?.material?1:0,p.__foundation?.opacity??1,w,h,0,0,cw,ch,0,0,same?1:0,liveBlend,0,liveAccumulation(p)?1:0,0,bandSectors,p.__legacyStarAa?1:0,0,...new Array(32).fill(0)]);const t=p.__foundation?.texture;if(t){out[32]=t.sizeMode==='relative'?1:0;out[33]=t.space==='tip'?1:0;out[34]=t.followDirection?1:0;out[35]=t.invert?1:0;out[36]=t.minimum;out[37]=t.aa?1:0;}return out;}

// GPU-only slots 12/15 carry rotation coefficients; canonical commands are untouched.
export const pack=cs=>{const a=new Float32Array(cs.length*STRIDE);cs.forEach((c,i)=>{const at=i*STRIDE;a.set(c,at);a[at+12]=Math.cos(c[4]);a[at+15]=Math.sin(c[4]);a[at+14]=c[22];});return a;};
// Snapshot end is frozen even though its append-only source may grow before rendering.
// Only unseen geometry is visited; superseding notifications never remove geometry.
export function publishedCommands(snapshot,v){
 if(snapshot.stableSource){const end=snapshot.stableEnd,start=v.stableCursor??0;if(!Number.isInteger(end)||end<start||end>snapshot.stableSource.length)throw Error('invalid stable snapshot cursor');const cs=snapshot.stableSource.slice(start,end);v.stableCursor=end;if(cs.length)v.index=cs.at(-1)[13];return cs;}
 const cs=(snapshot.stableCommands??[]).filter(c=>c[13]>v.index);if(cs.length)v.index=cs.at(-1)[13];return cs;
}
export function previewDirty(v,stable,live,width,height,dirty,tipTime=Infinity){v.fullTiles??=new Set;v.realKeys??=new Set;for(const c of stable)for(const key of keysFor(c,width,height)){v.keys.add(key);v.realKeys.add(key);if(!v.fullTiles.has(key))dirty.add(key);if(continuous(v.preset)&&solidTileCovered(c,key))v.fullTiles.add(key);}for(const key of v.tailKeys??[])if(!v.fullTiles.has(key))dirty.add(key);v.tailKeys=new Set;for(const c of live)for(const key of keysFor(c,width,height)){v.keys.add(key);v.tailKeys.add(key);if(c[20]<=tipTime)v.realKeys.add(key);if(!v.fullTiles.has(key))dirty.add(key);}}
export function sweepPrefixCommands(v,p,published,live=[]){
 const texture=p.__foundation.texture,stable=[],worldFixed=texture.space==='paper'&&texture.sizeMode==='absolute'&&!texture.followDirection;
 const same=(a,b)=>a&&b&&a[19]===2&&b[19]===2&&a[2]>=128&&a[18]===a[2]/2&&b[18]===a[18]&&a[0]===b[16]&&a[1]===b[17]&&[2,3,5,6,7,8,9,10].every(i=>a[i]===b[i]);
 let previous=v.sweepPrevious,r=0,required=1;
 for(let i=0;i<published.length;i++){const c=published[i],next=published[i+1]??live[0],length=next?Math.hypot(next[0]-next[16],next[1]-next[17]):0;
  if(worldFixed&&same(previous,c)&&same(c,next)&&length>.2&&Math.hypot(c[0]-c[16],c[1]-c[17])>.2){const q=c.slice();q[23]=-2;q[11]=Math.atan2(next[1]-next[17],next[0]-next[16]);q[20]=Math.asin(Math.min(1,.05/length))+.001;stable.push(q);r=Math.max(r,c[2]/2);const incoming=Math.atan2(c[1]-c[17],c[0]-c[16]),turn=((q[11]-incoming+Math.PI)%(Math.PI*2)+Math.PI*2)%(Math.PI*2)-Math.PI,extent=Math.abs(turn)+q[20]*2;required=Math.max(required,Math.ceil(extent/(2*Math.acos((c[2]/2+.5)/(c[2]/2+2)))));}else stable.push(c);
  previous=c;
 }
 v.sweepPrevious=previous;
 const sectors=2**Math.ceil(Math.log2(required));
 return {stable,prefixKeys:new Set,sectors,vertexCount:r?6+sectors*3:6};
}
export function livePrefixCommands(v,p,published,width,height,live=[]){const prefixKeys=new Set,stable=[];if(p.__foundation?.coverageUnion)return sweepPrefixCommands(v,p,published,live);if(!continuous(p))return {stable:published,prefixKeys,vertexCount:6};let old=v.circle;for(const c of published){let changed=false;for(const key of keysFor(c,width,height))if(!v.fullTiles?.has(key)){prefixKeys.add(key);changed=true;}if(changed){const incremental=c[2]>=256&&c[18]===c[2]/2&&old?.guaranteed&&old.x===c[16]&&old.y===c[17]&&old.r===c[18];if(incremental){const q=c.slice();q[23]=-1;stable.push(q);}else stable.push(c);}old={x:c[0],y:c[1],r:c[2]/2,guaranteed:!changed||c[18]===c[2]/2};}v.circle=old;const radii=stable.filter(c=>c[23]===-1).map(c=>c[2]/2),r=Math.max(0,...radii),required=r?Math.ceil(Math.PI/(2*Math.acos((r+.5)/(r+2)))):0,sectors=Math.max(16,2**Math.ceil(Math.log2(Math.max(1,required))));return {stable,prefixKeys,sectors,vertexCount:radii.length?sectors*12:6};}
function tileViewport(key,width,height,cw,ch){const [x,y]=key.split(',').map(Number),x0=Math.max(0,Math.floor(x*TILE*cw/width)),y0=Math.max(0,Math.floor(y*TILE*ch/height)),x1=Math.min(cw,Math.ceil((x+1)*TILE*cw/width)),y1=Math.min(ch,Math.ceil((y+1)*TILE*ch/height));return [x0,y0,Math.max(0,x1-x0),Math.max(0,y1-y0)];}
export function previewBatches(backend,states){
 const pending=states.filter(s=>s.id>backend.archivedThrough),batches=[];
 // Rebuild/undo/load can have committed tiles with no live feedback.
 // Still run the viewport compositor once so restored artwork becomes visible.
 if(!pending.length)return [{states:[],archive:false}];
 // Completed artwork is necessary scene geometry, not an obsolete display notification.
 // Keep every stroke; fold chronological groups into the archive in this submission.
 for(let i=0;i<pending.length;i+=4){const group=pending.slice(i,i+4),archive=i+4<pending.length;if(archive&&group.some(s=>!s.finished))throw Error('only ended feedback can be archived');batches.push({states:group,archive});}
 return batches;
}

export class TileDocument {
 constructor(width,height){if(!Number.isInteger(width)||!Number.isInteger(height)||width<1||height<1||width>8192||height>8192)throw Error('invalid dimensions');this.width=width;this.height=height;this.jobs=[];this.open=new Map;this.touched=new Map;this.count=0;this.knownTime=0;this.full=new Set;this.solidSeen=new Map;}
 append(id,preset,commands,keyFilter=null){const solid=continuous(preset);let seen=this.solidSeen.get(id);if(solid&&!seen)this.solidSeen.set(id,seen=new Set);let touched=this.touched.get(id);if(!touched)this.touched.set(id,touched=new Set);for(const c of commands)this.knownTime=Math.max(this.knownTime,c[20]);for(const c of commands){if(solid&&c[19]===1){const tag=[0,1,2,16,17,18].map(i=>Math.fround(c[i])).join(',');if(seen.has(tag))continue;seen.add(tag);}for(const key of keysFor(c,this.width,this.height)){if(keyFilter&&!keyFilter.has(key))continue;touched.add(key);const tag=id+':'+key;if(solid&&this.full.has(tag))continue;let j=this.open.get(tag);if(!j){j={id,key,preset,commands:[],offset:0,commit:false};this.jobs.push(j);this.open.set(tag,j);}j.commands.push(c);this.count++;}}}
 end(id,preset){const keys=[...(this.touched.get(id)??[])];for(const key of keys){this.open.delete(id+':'+key);this.jobs.push({id,key,preset,commands:[],offset:0,commit:true});}this.touched.delete(id);this.solidSeen.delete(id);return keys;}
 peek(){const j=this.jobs[0];if(!j)return null;return {...j,commands:j.commands.slice(j.offset,j.offset+16),t:j.commands[j.offset]?.[20]??null};}
 complete(job){const j=this.jobs[0];if(!j||j.id!==job.id||j.key!==job.key)throw Error('job ordering');if(!j.commit){if(continuous(j.preset)&&job.commands.some(c=>solidTileCovered(c,j.key)))this.full.add(j.id+':'+j.key);j.offset+=job.commands.length;this.count-=job.commands.length;}if(j.commit||j.offset===j.commands.length){this.jobs.shift();if(this.open.get(j.id+':'+j.key)===j)this.open.delete(j.id+':'+j.key);}}
 peekMany(limit=1){
 const out=[];let used=0;
 for(const j of this.jobs){if(used>=limit||out.length>=limit+32)break;const tag=j.id+':'+j.key;if(this.open.get(tag)===j)this.open.delete(tag);
 if(!j.commit&&continuous(j.preset)&&this.full.has(tag)){out.push({...j,commands:j.commands.slice(j.offset),t:j.commands[j.offset]?.[20]??null,skip:true});continue;}
 if(j.commit){out.push({...j,commands:[],t:null});used++;}else for(let offset=j.offset;offset<j.commands.length&&used<limit;offset+=16){out.push({...j,commands:j.commands.slice(offset,offset+16),t:j.commands[offset][20]});used++;}
 }return out;
}
 get oldestTime(){let t=Infinity;for(const j of this.jobs)if(!j.commit&&!this.full.has(j.id+':'+j.key))t=Math.min(t,j.commands[j.offset]?.[20]??Infinity);return t;}
 reset(){this.jobs=[];this.open.clear();this.touched.clear();this.count=0;this.knownTime=0;this.full.clear();this.solidSeen.clear();}
}
export class GpuRenderer {
 static async create(canvas,width,height,backend='auto'){
  if(backend!=='webgl2'&&navigator.gpu){try{const adapter=await navigator.gpu.requestAdapter({powerPreference:'high-performance'});if(adapter){const device=await adapter.requestDevice();const r=new WebGpuBackend(canvas,width,height,device,adapter);await r.initialize();return new GpuRenderer(r,width,height);}}catch(e){if(backend==='webgpu')throw e;}}
  if(backend==='webgpu')throw Error('WebGPU adapter unavailable');return new GpuRenderer(new WebGlBackend(canvas,width,height),width,height);
 }
 constructor(backend,width,height){this.backend=backend;this.document=new TileDocument(width,height);this.mailbox=new LatestMailbox;this.snapshot=null;this.inflight=false;this.completions=[];this.confirmedTime=0;this.errors=[];this.disposed=false;this.ended=new Set;this.formalQuantum=4;this.lastGpuWork=0;this.previewStates=new Map;this.confirmDelay=0;this.lastConfirmed=0;this.onComplete=null;this.needsFrame=true;}
 setLive(s){this.previewStates.set(s.id,s);this.mailbox.set(s);this.requestPreview();}
 // One deferred request consumes the newest notification after an input batch.
 // Do not launch a GPU submission for every coalesced input sample.
 requestPreview(){if(this.disposed||this.inflight||this.previewRequested||!this.backend.immediatePreview||!foundationUnion(this.mailbox.value?.preset)||this.mailbox.value.finished)return;this.previewRequested=true;queueMicrotask(()=>{this.previewRequested=false;this.frame(performance.now());});}
 markEnded(id){this.ended.add(id);}

 frame(now){if(this.disposed)return false;this.backend.poll?.();if(this.inflight)return false;const latest=this.mailbox.take();if(latest?.resetPreview)this.backend.retirePreview(latest.id);if(latest)this.snapshot=latest;const jobs=now-this.lastConfirmed>=this.confirmDelay?this.document.peekMany(this.snapshot&&!this.snapshot.finished?(this.lastGpuWork>32||this.snapshot.preset?.__foundation?.coverageUnion||(this.backend.immediatePreview&&foundationUnion(this.snapshot.preset))?0:1):this.formalQuantum):[],job=jobs[0]??null;if(!latest&&!job&&!this.needsFrame)return false;this.needsFrame=false;const s=this.snapshot;this.inflight=true;
  try{const submittedAt=performance.now();this.backend.render(s,jobs,[...this.previewStates.values()]).then(()=>{if(this.disposed)return;const end=performance.now();for(const j of jobs){this.document.complete(j);if(j.t!==null)this.confirmedTime=Math.max(this.confirmedTime,j.commands.at(-1)?.[20]??0);}if(job)this.lastConfirmed=end;const work=end-submittedAt;this.lastGpuWork=work;this.formalQuantum=work>50?Math.max(1,Math.floor(this.formalQuantum/2)):work<34?Math.min(8,this.formalQuantum+1):this.formalQuantum;
   if(s&&s.tip){const m={stage:'gpu-complete-proxy',revision:s.revision,completedAt:end,inputAge:end-s.tip.t,latestInputAge:end-(s.inputTip??s.tip).t,tip:{...s.tip},previewTip:{...(s.previewTip??s.tip)},previewQueueAge:this.mailbox.value?.tip?Math.max(0,end-(this.mailbox.value.inputTip??this.mailbox.value.tip).t):0,oldestQueueAge:Number.isFinite(this.document.oldestTime)?Math.max(0,end-this.document.oldestTime):0,confirmedLag:Math.max(0,(s.inputTip??s.tip).t-Math.min(this.document.knownTime,this.document.oldestTime)),obsoletePreviewCount:this.mailbox.obsolete+(this.backend.obsoleteFinished??0),formalJobs:this.document.jobs.length,inFlightSubmissions:1,gpuWorkMs:work,...(this.backend.lastSubmission?{submission:{...this.backend.lastSubmission}}:{})};this.completions.push(m);if(this.completions.length>24000)this.completions.splice(0,12000);this.onComplete?.(m);}for(const j of jobs)if(j.commit&&this.ended.has(j.id)&&!this.document.jobs.some(q=>q.id===j.id)){this.backend.retirePreview(j.id);this.previewStates.delete(j.id);this.ended.delete(j.id);if(this.snapshot?.id===j.id)this.snapshot=null;}
   this.inflight=false;this.needsFrame=!!job;this.requestPreview();}).catch(e=>{this.errors.push(e.message);this.inflight=false;this.disposed=true;});return true;
  }catch(e){this.errors.push(e.message);this.inflight=false;this.disposed=true;return false;}
 }
 async drain(finalFrame=true){const start=performance.now();while(this.inflight||this.document.jobs.length){if(performance.now()-start>120000)throw Error('confirmed renderer drain timeout');await new Promise(r=>requestAnimationFrame(r));this.frame(performance.now());}if(finalFrame){this.needsFrame=true;this.frame(performance.now());while(this.inflight){await new Promise(r=>requestAnimationFrame(r));this.backend.poll?.();}}if(this.errors.length)throw Error(this.errors.join(';'));}
 async read(){await this.drain();return this.backend.read();}
 async reset(){await this.drain();this.document.reset();this.backend.clear();this.snapshot=null;this.mailbox.value=null;this.ended.clear();this.previewStates.clear();this.confirmedTime=0;this.needsFrame=true;}
 async rebuildTiles(keys,entries){await this.drain(false);const filter=new Set(keys);if(!filter.size)return;this.backend.setPresentationHeld(true);let complete=false;try{this.backend.invalidateTiles(filter);this.needsFrame=true;for(const entry of entries){this.document.append(entry.id,entry.preset,entry.commands,filter);this.document.end(entry.id,entry.preset);}await this.drain();complete=true;}finally{this.backend.setPresentationHeld(false);}if(complete)await this.backend.presentCurrent();}
 async undoCommit(id){await this.drain(false);const ok=await this.backend.undoCommit(id);if(!ok)return false;this.needsFrame=true;await this.drain();return true;}
 async redoCommit(id){await this.drain(false);const ok=await this.backend.redoCommit(id);if(!ok)return false;this.needsFrame=true;await this.drain();return true;}
 dropHistory(ids){this.backend.dropHistory(ids);}
 destroy(){this.disposed=true;this.backend.destroy();}
 get info(){return this.backend.info;}
}
class WebGlBackend {
 constructor(canvas,width,height){this.canvas=canvas;this.width=width;this.height=height;this.presentationHeld=false;this.historyPatches=new Map;this.historyOrder=[];this.historyReservedBytes=0;this.historyRejectedId=-1;const gl=canvas.getContext('webgl2',{alpha:false,antialias:false,premultipliedAlpha:false,preserveDrawingBuffer:true,desynchronized:true});if(!gl||!gl.getExtension('EXT_color_buffer_float'))throw Error('WebGL2 float render targets unavailable');this.gl=gl;this.tiles=new Map;this.previews=new Map;this.dirtyConfirmed=new Set;this.archiveIds=new Map;this.archivedThrough=-1;this.obsoleteFinished=0;this.images=new Map;this.maskKeys=new WeakMap;this.resources=[];this.fence=null;this.pending=null;this.lost=false;canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.lost=true;this.pending?.reject(Error('GPU context lost; raw strokes remain exportable'));});this.deposit=this.program(B.glQuad,B.glDeposit);this.foundationDeposit=this.program(S.glQuad,S.glDeposit);this.live=this.program(B.glLiveVertex,B.glLive);this.foundationLive=this.program(S.glLiveVertex,S.glLive);this.solidLive=this.program(B.glLiveVertex,B.glSolidLive);this.display=this.program(S.glDisplayVertex,S.glDisplay);this.presentProgram=this.program(glPresentVertex,glPresent);this.vao=gl.createVertexArray();gl.bindVertexArray(this.vao);this.buffer=gl.createBuffer();this.liveTarget=this.surface(canvas.width,canvas.height,gl.RGBA8,gl.UNSIGNED_BYTE);this.archiveTarget=this.surface(canvas.width,canvas.height,gl.RGBA8,gl.UNSIGNED_BYTE);this.zeroStroke=this.surface(TILE,TILE,gl.RGBA32F,gl.FLOAT);this.zeroLayer=this.surface(TILE,TILE,gl.RGBA8,gl.UNSIGNED_BYTE);this.defaultImage=this.image(null);this.zeroLive=this.surface(this.canvas.width,this.canvas.height,this.gl.RGBA16F,this.gl.HALF_FLOAT);this.info={backend:'WebGL2',desynchronized:!!gl.getContextAttributes().desynchronized,renderer:gl.getParameter(gl.RENDERER),hardwareVerified:false};}
 program(v,f){const g=this.gl,p=g.createProgram();for(const [kind,src] of [[g.VERTEX_SHADER,v],[g.FRAGMENT_SHADER,f]]){const s=g.createShader(kind);g.shaderSource(s,src);g.compileShader(s);if(!g.getShaderParameter(s,g.COMPILE_STATUS))throw Error(g.getShaderInfoLog(s));g.attachShader(p,s);g.deleteShader(s);}g.linkProgram(p);if(!g.getProgramParameter(p,g.LINK_STATUS))throw Error(g.getProgramInfoLog(p));this.resources.push(['program',p]);return p;}
 surface(w,h,format,type,withDepth=false){const g=this.gl,t=g.createTexture();g.bindTexture(g.TEXTURE_2D,t);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.NEAREST);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.NEAREST);g.texImage2D(g.TEXTURE_2D,0,format,w,h,0,g.RGBA,type,null);const f=g.createFramebuffer();g.bindFramebuffer(g.FRAMEBUFFER,f);g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT0,g.TEXTURE_2D,t,0);let depth=null;if(withDepth){depth=g.createRenderbuffer();g.bindRenderbuffer(g.RENDERBUFFER,depth);g.renderbufferStorage(g.RENDERBUFFER,g.DEPTH_COMPONENT16,w,h);g.framebufferRenderbuffer(g.FRAMEBUFFER,g.DEPTH_ATTACHMENT,g.RENDERBUFFER,depth);}if(g.checkFramebufferStatus(g.FRAMEBUFFER)!==g.FRAMEBUFFER_COMPLETE)throw Error('incomplete framebuffer');g.clearColor(0,0,0,0);g.depthMask(true);g.clearDepth(1);g.clear(g.COLOR_BUFFER_BIT|(depth?g.DEPTH_BUFFER_BIT:0));return {t,f,w,h,depth};}
 release(a){const g=this.gl;g.deleteTexture(a.t);if(a.f)g.deleteFramebuffer(a.f);if(a.depth)g.deleteRenderbuffer(a.depth);}
 copySurface(src,dst){const g=this.gl;g.bindFramebuffer(g.READ_FRAMEBUFFER,src.f);g.bindFramebuffer(g.DRAW_FRAMEBUFFER,dst.f);g.blitFramebuffer(0,0,TILE,TILE,0,0,TILE,TILE,g.COLOR_BUFFER_BIT,g.NEAREST);}
 historyTouch(id){const i=this.historyOrder.indexOf(id);if(i>=0)this.historyOrder.splice(i,1);this.historyOrder.push(id);}
 historyRelease(id){const patch=this.historyPatches.get(id);if(!patch)return;for(const p of patch.tiles.values()){this.release(p.before);if(p.after)this.release(p.after);}this.historyReservedBytes=Math.max(0,this.historyReservedBytes-patch.tiles.size*HISTORY_TILE_RESERVATION);this.historyPatches.delete(id);const i=this.historyOrder.indexOf(id);if(i>=0)this.historyOrder.splice(i,1);}
 historyReserve(id){while(this.historyReservedBytes+HISTORY_TILE_RESERVATION>HISTORY_GPU_BUDGET){const victim=this.historyOrder.find(x=>x!==id);if(victim===undefined)return false;this.historyRelease(victim);}this.historyReservedBytes+=HISTORY_TILE_RESERVATION;return true;}
 captureBefore(id,key,t,preset){if(this.historyRejectedId===id)return;let patch=this.historyPatches.get(id);if(!patch){patch={state:'applied',tiles:new Map};this.historyPatches.set(id,patch);this.historyTouch(id);}if(patch.tiles.has(key))return;if(!this.historyReserve(id)){this.historyRelease(id);this.historyRejectedId=id;return;}const before=this.surface(TILE,TILE,this.gl.RGBA8,this.gl.UNSIGNED_BYTE);this.copySurface(t.layer[t.l],before);patch.tiles.set(key,{before,after:null,beforeCommittedId:t.committedId??-1,beforePreset:t.preset,afterPreset:preset,beforeArchiveId:this.archiveIds.get(key),afterArchiveId:undefined});}
 async undoCommit(id){const patch=this.historyPatches.get(id);if(!patch||patch.state!=='applied')return false;for(const [key,p] of patch.tiles){const t=this.tiles.get(key);if(!t)return false;if(!p.after){p.after=this.surface(TILE,TILE,this.gl.RGBA8,this.gl.UNSIGNED_BYTE);this.copySurface(t.layer[t.l],p.after);p.afterArchiveId=this.archiveIds.get(key);}this.copySurface(p.before,t.layer[t.l]);t.committedId=p.beforeCommittedId;t.preset=p.beforePreset;if(p.beforeArchiveId===undefined)this.archiveIds.delete(key);else this.archiveIds.set(key,p.beforeArchiveId);this.dirtyConfirmed.add(key);}patch.state='undone';this.historyTouch(id);return true;}
 async redoCommit(id){const patch=this.historyPatches.get(id);if(!patch||patch.state!=='undone')return false;for(const [key,p] of patch.tiles){const t=this.tiles.get(key);if(!t||!p.after)return false;this.copySurface(p.after,t.layer[t.l]);t.committedId=id;t.preset=p.afterPreset;if(p.afterArchiveId===undefined)this.archiveIds.delete(key);else this.archiveIds.set(key,p.afterArchiveId);this.dirtyConfirmed.add(key);}patch.state='applied';this.historyTouch(id);return true;}
 dropHistory(ids){for(const id of ids)this.historyRelease(id);}
 setPresentationHeld(held){this.presentationHeld=held;}
 async presentCurrent(){const g=this.gl;g.bindFramebuffer(g.FRAMEBUFFER,null);g.viewport(0,0,this.canvas.width,this.canvas.height);g.disable(g.BLEND);g.useProgram(this.presentProgram);g.activeTexture(g.TEXTURE0);g.bindTexture(g.TEXTURE_2D,this.liveTarget.t);g.uniform1i(g.getUniformLocation(this.presentProgram,'source'),0);g.drawArrays(g.TRIANGLES,0,3);g.flush();}
 image(mask){let key=mask?this.maskKeys.get(mask):'default';if(mask&&!key){key=JSON.stringify(mask);this.maskKeys.set(mask,key);}if(this.images.has(key))return this.images.get(key);const g=this.gl,w=mask?.width??1,h=mask?.height??1,a=new Uint8Array(w*h*4);for(let i=0;i<w*h;i++)a[i*4]=Math.round((mask?.alpha[i]??1)*255);const s=this.surface(w,h,g.RGBA8,g.UNSIGNED_BYTE);g.bindTexture(g.TEXTURE_2D,s.t);g.texSubImage2D(g.TEXTURE_2D,0,0,0,w,h,g.RGBA,g.UNSIGNED_BYTE,a);this.images.set(key,s);return s;}
 tile(key){let t=this.tiles.get(key);if(!t){if(this.tiles.size>=1024)throw Error('document tile limit');const [x,y]=key.split(',').map(Number);t={x:x*TILE,y:y*TILE,layer:[this.surface(TILE,TILE,this.gl.RGBA8,this.gl.UNSIGNED_BYTE),this.surface(TILE,TILE,this.gl.RGBA8,this.gl.UNSIGNED_BYTE)],l:0,stroke:null,s:0,active:null,preset:emptyPreset};this.tiles.set(key,t);}return t;}
 use(program,params,textures={}){const g=this.gl;g.useProgram(program);g.uniform4fv(g.getUniformLocation(program,'params'),params);let i=0;for(const [name,s]of Object.entries(textures)){g.activeTexture(g.TEXTURE0+i);g.bindTexture(g.TEXTURE_2D,s.t);g.uniform1i(g.getUniformLocation(program,name),i++);}}
 render(snapshot,jobs,states=[]){const dirty=new Set(this.dirtyConfirmed);this.dirtyConfirmed.clear();const g=this.gl;if(this.lost)throw Error('GPU context lost');g.bindVertexArray(this.vao);const live=snapshot?.commands??[],p=snapshot?.preset??emptyPreset,mp=this.image(p.mask),gp=this.image(p.texture);
  for(const batch of previewBatches(this,states)){for(const snapshot of batch.states){const p=snapshot.preset,live=snapshot.commands??[],mp=this.image(p.mask),gp=this.image(p.texture);let v=this.previews.get(snapshot.id);if(!v){v={id:snapshot.id,preset:p,prefix:this.surface(this.canvas.width,this.canvas.height,g.RGBA16F,g.HALF_FLOAT,continuous(p)),tail:this.surface(this.canvas.width,this.canvas.height,g.RGBA16F,g.HALF_FLOAT),index:-1,keys:new Set};this.previews.set(v.id,v);}const published=publishedCommands(snapshot,v);const {stable,prefixKeys,vertexCount,sectors}=livePrefixCommands(v,p,published,this.width,this.height,live);previewDirty(v,stable,live,this.width,this.height,dirty,snapshot.inputTip?.t??snapshot.tip?.t??Infinity);for(const [target,commands,clear]of [[v.prefix,stable,false],[v.tail,live,true]]){g.bindFramebuffer(g.FRAMEBUFFER,target.f);g.viewport(0,0,this.canvas.width,this.canvas.height);if(clear){g.clearColor(0,0,0,0);g.clear(g.COLOR_BUFFER_BIT);}const depth=!clear&&target.depth;if(depth){g.enable(g.DEPTH_TEST);g.depthFunc(g.LESS);g.depthMask(false);}else g.disable(g.DEPTH_TEST);g.enable(g.BLEND);g.blendEquation(liveAccumulation(p)?g.FUNC_ADD:g.MAX);g.blendFunc(g.ONE,liveAccumulation(p)?g.ONE_MINUS_SRC_ALPHA:g.ONE);this.use(continuous(p)?this.solidLive:p.__foundation?this.foundationLive:this.live,parameters(p,0,0,commands.length,0,this.width,this.height,this.canvas.width,this.canvas.height,false,0,sectors),{maskImage:mp,grainImage:gp});g.bindBuffer(g.ARRAY_BUFFER,this.buffer);g.bufferData(g.ARRAY_BUFFER,pack(commands),g.DYNAMIC_DRAW);for(let i=0;i<6;i++){g.enableVertexAttribArray(i);g.vertexAttribPointer(i,4,g.FLOAT,false,96,i*16);g.vertexAttribDivisor(i,1);}const clips=[null];for(const clip of clips){if(clip){if(!clip[2]||!clip[3])continue;g.enable(g.SCISSOR_TEST);g.scissor(clip[0],this.canvas.height-clip[1]-clip[3],clip[2],clip[3]);}g.depthMask(false);this.use(continuous(p)?this.solidLive:p.__foundation?this.foundationLive:this.live,parameters(p,0,0,commands.length,0,this.width,this.height,this.canvas.width,this.canvas.height,false,0,sectors),{maskImage:mp,grainImage:gp});g.drawArraysInstanced(g.TRIANGLES,0,clear?6:vertexCount,commands.length);if(depth){g.depthMask(true);this.use(continuous(p)?this.solidLive:p.__foundation?this.foundationLive:this.live,parameters(p,0,0,commands.length,1,this.width,this.height,this.canvas.width,this.canvas.height,false,0,sectors),{maskImage:mp,grainImage:gp});g.drawArraysInstanced(g.TRIANGLES,0,clear?6:vertexCount,commands.length);}}g.disable(g.SCISSOR_TEST);g.disable(g.DEPTH_TEST);g.depthMask(true);for(let i=0;i<6;i++){g.disableVertexAttribArray(i);g.vertexAttribDivisor(i,0);}g.disable(g.BLEND);}}
  const overlays=[];for(const v of this.previews.values()){overlays.push({id:v.id,preset:v.preset,texture:v.prefix},{id:v.id,preset:v.preset,texture:v.tail});}
  const keys=dirty;
  g.bindFramebuffer(g.FRAMEBUFFER,this.liveTarget.f);g.viewport(0,0,this.canvas.width,this.canvas.height);for(const key of keys){const t=this.tiles.get(key),[tx,ty]=key.split(',').map(Number),tp=t?.preset??emptyPreset,params=parameters(tp,tx*TILE,ty*TILE,0,0,this.width,this.height,this.canvas.width,this.canvas.height);params[24]=t?.active??-1;params[25]=t?.committedId??-1;params[26]=overlays.length;params[28]=this.archiveIds.get(key)??-1;const textures={layer:t?.layer[t.l]??this.zeroLayer,src:t?.stroke?.[t.s]??this.zeroStroke,archiveImage:this.archiveTarget};for(let i=0;i<8;i++){textures['liveImage'+i]=overlays[i]?.texture??this.zeroLive;params[32+i*4]=overlays[i]?.id??-1;params[33+i*4]=S.blends[overlays[i]?.preset.blend??'normal'];params[34+i*4]=overlays[i]?.preset.__foundation?.opacity??overlays[i]?.preset.opacity??1;params[35+i*4]=overlays[i]?.preset.__foundation?.coverageUnion?3:overlays[i]?.preset.__foundation?.material?2:overlays[i]&&liveAccumulation(overlays[i].preset)?1:0;}this.use(this.display,params,textures);g.drawArrays(g.TRIANGLES,0,6);}

  if(batch.archive){g.bindFramebuffer(g.READ_FRAMEBUFFER,this.liveTarget.f);g.bindFramebuffer(g.DRAW_FRAMEBUFFER,this.archiveTarget.f);g.blitFramebuffer(0,0,this.canvas.width,this.canvas.height,0,0,this.canvas.width,this.canvas.height,g.COLOR_BUFFER_BIT,g.NEAREST);for(const v of this.previews.values()){this.archivedThrough=Math.max(this.archivedThrough,v.id);for(const key of v.realKeys??[])this.archiveIds.set(key,Math.max(this.archiveIds.get(key)??-1,v.id));this.release(v.prefix);this.release(v.tail);}this.previews.clear();}dirty.clear();}
  if(!this.presentationHeld)await this.presentCurrent();
  for(const job of jobs){if(job.skip)continue;this.dirtyConfirmed.add(job.key);const t=this.tile(job.key),solid=continuous(job.preset);if(!job.commit)this.captureBefore(job.id,job.key,t,job.preset);if(t.active!==job.id&&!job.commit){if(t.stroke)for(const s of t.stroke)this.release(s);t.stroke=[this.surface(TILE,TILE,solid?g.RGBA16F:g.RGBA32F,solid?g.HALF_FLOAT:g.FLOAT),this.surface(TILE,TILE,solid?g.RGBA16F:g.RGBA32F,solid?g.HALF_FLOAT:g.FLOAT)];t.s=0;t.active=job.id;t.preset=job.preset;}if(!t.stroke)throw Error('commit has no stroke');const target=job.commit?t.layer[1-t.l]:t.stroke[solid?t.s:1-t.s];g.bindFramebuffer(g.FRAMEBUFFER,target.f);g.viewport(0,0,TILE,TILE);if(solid&&!job.commit){g.enable(g.BLEND);g.blendEquation(g.MAX);g.blendFunc(g.ONE,g.ONE);this.use(this.solidLive,parameters(job.preset,t.x,t.y,job.commands.length,2,TILE,TILE,TILE,TILE),{maskImage:this.image(job.preset.mask),grainImage:this.image(job.preset.texture)});g.bindBuffer(g.ARRAY_BUFFER,this.buffer);g.bufferData(g.ARRAY_BUFFER,pack(job.commands),g.DYNAMIC_DRAW);for(let i=0;i<6;i++){g.enableVertexAttribArray(i);g.vertexAttribPointer(i,4,g.FLOAT,false,96,i*16);g.vertexAttribDivisor(i,1);}g.drawArraysInstanced(g.TRIANGLES,0,6,job.commands.length);for(let i=0;i<6;i++){g.disableVertexAttribArray(i);g.vertexAttribDivisor(i,0);}g.disable(g.BLEND);}else{const params=parameters(job.preset,t.x,t.y,job.commands.length,job.commit?1:0);const program=job.preset.__foundation?this.foundationDeposit:this.deposit;this.use(program,params,{src:t.stroke[t.s],layer:t.layer[t.l],maskImage:this.image(job.preset.mask),grainImage:this.image(job.preset.texture)});const data=new Float32Array(96*4);data.set(pack(job.commands));g.uniform4fv(g.getUniformLocation(program,'commands'),data);g.drawArrays(g.TRIANGLES,0,3);}if(job.commit){t.l=1-t.l;t.committedId=job.id;t.active=null;if((this.archiveIds.get(job.key)??Infinity)<=job.id)this.archiveIds.delete(job.key);for(const s of t.stroke)this.release(s);t.stroke=null;}else if(!solid)t.s=1-t.s;}
  const err=g.getError();if(err!==g.NO_ERROR)throw Error('WebGL error '+err);this.fence=g.fenceSync(g.SYNC_GPU_COMMANDS_COMPLETE,0);g.flush();return new Promise((resolve,reject)=>{this.pending={resolve,reject};});
 }
 poll(){if(!this.fence)return;const g=this.gl,s=g.clientWaitSync(this.fence,0,0);if(s===g.ALREADY_SIGNALED||s===g.CONDITION_SATISFIED){g.deleteSync(this.fence);this.fence=null;const p=this.pending;this.pending=null;p.resolve();}else if(s===g.WAIT_FAILED){this.pending.reject(Error('GPU fence failed'));this.pending=null;}}
 readViewport(){const g=this.gl,w=this.canvas.width,h=this.canvas.height,a=new Uint8Array(w*h*4),out=new Uint8ClampedArray(a.length);g.bindFramebuffer(g.FRAMEBUFFER,this.liveTarget.f);g.readPixels(0,0,w,h,g.RGBA,g.UNSIGNED_BYTE,a);for(let y=0;y<h;y++)out.set(a.subarray((h-1-y)*w*4,(h-y)*w*4),y*w*4);return out;}
 read(){const g=this.gl,out=new Uint8ClampedArray(this.width*this.height*4);for(const t of this.tiles.values()){g.bindFramebuffer(g.FRAMEBUFFER,t.layer[t.l].f);const a=new Uint8Array(TILE*TILE*4);g.readPixels(0,0,TILE,TILE,g.RGBA,g.UNSIGNED_BYTE,a);for(let y=0;y<TILE&&t.y+y<this.height;y++){const n=Math.min(TILE,this.width-t.x);out.set(a.subarray(y*TILE*4,(y*TILE+n)*4),((t.y+y)*this.width+t.x)*4);}}return out;}
 retirePreview(id){const v=this.previews.get(id);if(v){for(const key of v.keys)this.dirtyConfirmed.add(key);this.release(v.prefix);this.release(v.tail);this.previews.delete(id);}}
 invalidateTiles(keys){for(const key of keys){const t=this.tiles.get(key);if(t){for(const s of t.layer)this.release(s);if(t.stroke)for(const s of t.stroke)this.release(s);this.tiles.delete(key);}this.archiveIds.delete(key);this.dirtyConfirmed.add(key);}}
 clear(){for(const id of this.previews.keys())this.retirePreview(id);for(const id of [...this.historyPatches.keys()])this.historyRelease(id);for(const t of this.tiles.values()){for(const s of t.layer)this.release(s);if(t.stroke)for(const s of t.stroke)this.release(s);}this.tiles.clear();this.dirtyConfirmed.clear();this.archiveIds.clear();this.archivedThrough=-1;this.gl.bindFramebuffer(this.gl.FRAMEBUFFER,this.liveTarget.f);this.gl.clearColor(0,0,0,0);this.gl.clear(this.gl.COLOR_BUFFER_BIT);}
 destroy(){this.clear();for(const s of this.images.values())this.release(s);this.release(this.liveTarget);this.release(this.archiveTarget);this.release(this.zeroLive);this.release(this.zeroStroke);this.release(this.zeroLayer);for(const [_,p]of this.resources)this.gl.deleteProgram(p);this.gl.deleteBuffer(this.buffer);this.gl.deleteVertexArray(this.vao);}
}
class WebGpuBackend {
 // WebGPU resolves completion independently; WebGL fences are polled by the RAF loop.
 constructor(canvas,width,height,device,adapter){this.immediatePreview=true;this.canvas=canvas;this.width=width;this.height=height;this.presentationHeld=false;this.historyPatches=new Map;this.historyOrder=[];this.historyReservedBytes=0;this.historyRejectedId=-1;this.device=device;this.adapter=adapter;this.tiles=new Map;this.previews=new Map;this.dirtyConfirmed=new Set;this.archiveIds=new Map;this.archivedThrough=-1;this.obsoleteFinished=0;this.images=new Map;this.maskKeys=new WeakMap;this.transient=[];this.error=null;this.device.lost.then(i=>{this.error=Error('GPU device lost: '+i.reason+'; raw strokes remain exportable');});this.device.addEventListener('uncapturederror',e=>{this.error=e.error;});this.info={backend:'WebGPU',adapter:adapter.info?.description??'unspecified',hardwareVerified:false,desynchronized:false};}
 async initialize(){const d=this.device;this.format=navigator.gpu.getPreferredCanvasFormat();const tex=(binding,sampleType='unfilterable-float')=>({binding,visibility:GPUShaderStage.COMPUTE|GPUShaderStage.FRAGMENT,texture:{sampleType}});const u={binding:0,visibility:GPUShaderStage.COMPUTE|GPUShaderStage.VERTEX|GPUShaderStage.FRAGMENT,buffer:{type:'uniform'}};
  this.depositLayout=d.createBindGroupLayout({entries:[u,tex(1),{binding:2,visibility:GPUShaderStage.COMPUTE,storageTexture:{access:'write-only',format:'rgba32float'}},{binding:3,visibility:GPUShaderStage.COMPUTE,buffer:{type:'read-only-storage'}},tex(4),tex(5),tex(6),{binding:7,visibility:GPUShaderStage.COMPUTE,storageTexture:{access:'write-only',format:'rgba8unorm'}}]});
  this.liveLayout=d.createBindGroupLayout({entries:[u,{binding:1,visibility:GPUShaderStage.VERTEX,buffer:{type:'read-only-storage'}},tex(2),tex(3)]});this.displayLayout=d.createBindGroupLayout({entries:[u,tex(1),tex(2),...Array.from({length:8},(_,i)=>tex(i+3)),tex(11)]});
  d.pushErrorScope('validation');const module=code=>d.createShaderModule({code});for(const code of [S.wgDeposit,S.wgLive,S.wgDisplay]){const info=await module(code).getCompilationInfo();const errors=info.messages.filter(x=>x.type==='error');if(errors.length)throw Error(errors.map(x=>x.message).join('\n'));}
  this.deposit=await d.createComputePipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[this.depositLayout]}),compute:{module:module(B.wgDeposit),entryPoint:'main'}});
  this.live=await d.createRenderPipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[this.liveLayout]}),vertex:{module:module(B.wgLive),entryPoint:'vertex'},fragment:{module:module(B.wgLive),entryPoint:'fragment',targets:[{format:'rgba16float',blend:{color:{operation:'max',srcFactor:'one',dstFactor:'one'},alpha:{operation:'max',srcFactor:'one',dstFactor:'one'}}}]},primitive:{topology:'triangle-list'}});
  this.liveSolid=await d.createRenderPipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[this.liveLayout]}),vertex:{module:module(B.wgLive),entryPoint:'vertex'},fragment:{module:module(B.wgLive),entryPoint:'fragmentSolid',targets:[{format:'rgba16float',blend:{color:{operation:'max',srcFactor:'one',dstFactor:'one'},alpha:{operation:'max',srcFactor:'one',dstFactor:'one'}}}]},primitive:{topology:'triangle-list'}});
  this.liveFlow=await d.createRenderPipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[this.liveLayout]}),vertex:{module:module(B.wgLive),entryPoint:'vertex'},fragment:{module:module(B.wgLive),entryPoint:'fragment',targets:[{format:'rgba16float',blend:{color:{operation:'add',srcFactor:'one',dstFactor:'one-minus-src-alpha'},alpha:{operation:'add',srcFactor:'one',dstFactor:'one-minus-src-alpha'}}}]},primitive:{topology:'triangle-list'}});
  const depthPipeline=(entry,write)=>d.createRenderPipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[this.liveLayout]}),vertex:{module:module(B.wgLive),entryPoint:'vertex'},fragment:{module:module(B.wgLive),entryPoint:entry,targets:[{format:'rgba16float',blend:{color:{operation:'max',srcFactor:'one',dstFactor:'one'},alpha:{operation:'max',srcFactor:'one',dstFactor:'one'}}}]},primitive:{topology:'triangle-list'},depthStencil:{format:'depth24plus',depthWriteEnabled:write,depthCompare:'less'}});this.liveDepth=await depthPipeline('fragmentSolid',false);this.liveOpaque=await depthPipeline('fragmentOpaqueSolid',true);
  this.foundationDeposit=await d.createComputePipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[this.depositLayout]}),compute:{module:module(S.wgDeposit),entryPoint:'main'}});
  this.foundationLive=await d.createRenderPipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[this.liveLayout]}),vertex:{module:module(S.wgLive),entryPoint:'vertex'},fragment:{module:module(S.wgLive),entryPoint:'fragment',targets:[{format:'rgba16float',blend:{color:{operation:'max',srcFactor:'one',dstFactor:'one'},alpha:{operation:'max',srcFactor:'one',dstFactor:'one'}}}]},primitive:{topology:'triangle-list'}});
  this.foundationSweep=await d.createRenderPipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[this.liveLayout]}),vertex:{module:module(S.wgLive),entryPoint:'vertex'},fragment:{module:module(S.wgLive),entryPoint:'fragmentSweep',targets:[{format:'rgba16float',blend:{color:{operation:'max',srcFactor:'one',dstFactor:'one'},alpha:{operation:'max',srcFactor:'one',dstFactor:'one'}}}]},primitive:{topology:'triangle-list'}});
  this.foundationSweepPlain=await d.createRenderPipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[this.liveLayout]}),vertex:{module:module(S.wgLive),entryPoint:'vertex'},fragment:{module:module(S.wgLive),entryPoint:'fragmentSweepPlain',targets:[{format:'rgba16float',blend:{color:{operation:'max',srcFactor:'one',dstFactor:'one'},alpha:{operation:'max',srcFactor:'one',dstFactor:'one'}}}]},primitive:{topology:'triangle-list'}});
  this.foundationFlow=await d.createRenderPipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[this.liveLayout]}),vertex:{module:module(S.wgLive),entryPoint:'vertex'},fragment:{module:module(S.wgLive),entryPoint:'fragment',targets:[{format:'rgba16float',blend:{color:{operation:'add',srcFactor:'one',dstFactor:'one-minus-src-alpha'},alpha:{operation:'add',srcFactor:'one',dstFactor:'one-minus-src-alpha'}}}]},primitive:{topology:'triangle-list'}});
  this.sweepDisplay=await d.createRenderPipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[this.displayLayout]}),vertex:{module:module(S.wgDisplay),entryPoint:'vertex'},fragment:{module:module(S.wgDisplay),entryPoint:'fragmentSweepDisplay',targets:[{format:this.format}]},primitive:{topology:'triangle-list'}});
  this.display=await d.createRenderPipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[this.displayLayout]}),vertex:{module:module(S.wgDisplay),entryPoint:'vertex'},fragment:{module:module(S.wgDisplay),entryPoint:'fragment',targets:[{format:this.format}]},primitive:{topology:'triangle-list'}});const presentModule=module(wgPresent);const presentInfo=await presentModule.getCompilationInfo();const presentErrors=presentInfo.messages.filter(x=>x.type==='error');if(presentErrors.length)throw Error(presentErrors.map(x=>x.message).join('\n'));this.present=await d.createRenderPipelineAsync({layout:'auto',vertex:{module:presentModule,entryPoint:'vertex'},fragment:{module:presentModule,entryPoint:'fragment',targets:[{format:this.format}]},primitive:{topology:'triangle-list'}});const error=await d.popErrorScope();if(error)throw error;
  this.context=this.canvas.getContext('webgpu');this.context.configure({device:d,format:this.format,alphaMode:'opaque',usage:GPUTextureUsage.RENDER_ATTACHMENT});this.liveTarget=d.createTexture({size:[this.canvas.width,this.canvas.height],format:this.format,usage:GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_SRC|GPUTextureUsage.COPY_DST});this.archiveTarget=d.createTexture({size:[this.canvas.width,this.canvas.height],format:this.format,usage:GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_SRC|GPUTextureUsage.COPY_DST});this.zeroStroke=this.texture(TILE,TILE,'rgba32float');this.zeroLayer=this.texture(TILE,TILE,'rgba8unorm');this.defaultImage=this.image(null);this.zeroLive=this.texture(this.canvas.width,this.canvas.height,'rgba16float');
 }
 texture(w,h,format){return this.device.createTexture({size:[w,h],format,usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.STORAGE_BINDING|GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.COPY_SRC|GPUTextureUsage.COPY_DST});}
 image(mask){let key=mask?this.maskKeys.get(mask):'default';if(mask&&!key){key=JSON.stringify(mask);this.maskKeys.set(mask,key);}if(this.images.has(key))return this.images.get(key);const w=mask?.width??1,h=mask?.height??1,a=new Uint8Array(w*h*4);for(let i=0;i<w*h;i++)a[i*4]=Math.round((mask?.alpha[i]??1)*255);const t=this.texture(w,h,'rgba8unorm');this.device.queue.writeTexture({texture:t},a,{bytesPerRow:w*4},[w,h]);this.images.set(key,t);return t;}
 buffer(a,usage){const b=this.device.createBuffer({size:Math.max(16,a.byteLength),usage:usage|GPUBufferUsage.COPY_DST});this.device.queue.writeBuffer(b,0,a);this.transient.push(b);return b;}
 group(layout,entries){return this.device.createBindGroup({layout,entries:entries.map((resource,binding)=>({binding,resource:resource.createView?resource.createView():{buffer:resource}}))});}
 tile(key){let t=this.tiles.get(key);if(!t){if(this.tiles.size>=1024)throw Error('document tile limit');const [x,y]=key.split(',').map(Number);t={x:x*TILE,y:y*TILE,layer:[this.texture(TILE,TILE,'rgba8unorm'),this.texture(TILE,TILE,'rgba8unorm')],l:0,stroke:null,s:0,active:null,preset:emptyPreset};this.tiles.set(key,t);}return t;}
 historyTouch(id){const i=this.historyOrder.indexOf(id);if(i>=0)this.historyOrder.splice(i,1);this.historyOrder.push(id);}
 historyRelease(id){const patch=this.historyPatches.get(id);if(!patch)return;for(const p of patch.tiles.values()){p.before.destroy();p.after?.destroy();}this.historyReservedBytes=Math.max(0,this.historyReservedBytes-patch.tiles.size*HISTORY_TILE_RESERVATION);this.historyPatches.delete(id);const i=this.historyOrder.indexOf(id);if(i>=0)this.historyOrder.splice(i,1);}
 historyReserve(id){while(this.historyReservedBytes+HISTORY_TILE_RESERVATION>HISTORY_GPU_BUDGET){const victim=this.historyOrder.find(x=>x!==id);if(victim===undefined)return false;this.historyRelease(victim);}this.historyReservedBytes+=HISTORY_TILE_RESERVATION;return true;}
 captureBefore(id,key,t,preset,e){if(this.historyRejectedId===id)return;let patch=this.historyPatches.get(id);if(!patch){patch={state:'applied',tiles:new Map};this.historyPatches.set(id,patch);this.historyTouch(id);}if(patch.tiles.has(key))return;if(!this.historyReserve(id)){this.historyRelease(id);this.historyRejectedId=id;return;}const before=this.texture(TILE,TILE,'rgba8unorm');e.copyTextureToTexture({texture:t.layer[t.l]},{texture:before},[TILE,TILE]);patch.tiles.set(key,{before,after:null,beforeCommittedId:t.committedId??-1,beforePreset:t.preset,afterPreset:preset,beforeArchiveId:this.archiveIds.get(key),afterArchiveId:undefined});}
 async undoCommit(id){const patch=this.historyPatches.get(id);if(!patch||patch.state!=='applied')return false;const e=this.device.createCommandEncoder();for(const [key,p] of patch.tiles){const t=this.tiles.get(key);if(!t)return false;if(!p.after){p.after=this.texture(TILE,TILE,'rgba8unorm');e.copyTextureToTexture({texture:t.layer[t.l]},{texture:p.after},[TILE,TILE]);p.afterArchiveId=this.archiveIds.get(key);}e.copyTextureToTexture({texture:p.before},{texture:t.layer[t.l]},[TILE,TILE]);t.committedId=p.beforeCommittedId;t.preset=p.beforePreset;if(p.beforeArchiveId===undefined)this.archiveIds.delete(key);else this.archiveIds.set(key,p.beforeArchiveId);this.dirtyConfirmed.add(key);}this.device.queue.submit([e.finish()]);await this.device.queue.onSubmittedWorkDone();patch.state='undone';this.historyTouch(id);return true;}
 async redoCommit(id){const patch=this.historyPatches.get(id);if(!patch||patch.state!=='undone')return false;const e=this.device.createCommandEncoder();for(const [key,p] of patch.tiles){const t=this.tiles.get(key);if(!t||!p.after)return false;e.copyTextureToTexture({texture:p.after},{texture:t.layer[t.l]},[TILE,TILE]);t.committedId=id;t.preset=p.afterPreset;if(p.afterArchiveId===undefined)this.archiveIds.delete(key);else this.archiveIds.set(key,p.afterArchiveId);this.dirtyConfirmed.add(key);}this.device.queue.submit([e.finish()]);await this.device.queue.onSubmittedWorkDone();patch.state='applied';this.historyTouch(id);return true;}
 dropHistory(ids){for(const id of ids)this.historyRelease(id);}
 setPresentationHeld(held){this.presentationHeld=held;}
 async presentCurrent(){const d=this.device,e=d.createCommandEncoder(),p=e.beginRenderPass({colorAttachments:[{view:this.context.getCurrentTexture().createView(),clearValue:{r:1,g:1,b:1,a:1},loadOp:'clear',storeOp:'store'}]});p.setPipeline(this.present);p.setBindGroup(0,d.createBindGroup({layout:this.present.getBindGroupLayout(0),entries:[{binding:0,resource:this.liveTarget.createView()}]}));p.draw(3);p.end();d.queue.submit([e.finish()]);await d.queue.onSubmittedWorkDone();}
 async render(snapshot,jobs,states=[]){const submissionStart=performance.now(),diagnostics={publishedCommands:0,liveCommands:0,dirtyTiles:0};const dirty=new Set(this.dirtyConfirmed);this.dirtyConfirmed.clear();if(this.error)throw this.error;const d=this.device,e=d.createCommandEncoder(),live=snapshot?.commands??[],p=snapshot?.preset??emptyPreset;const uniform=a=>this.buffer(a,GPUBufferUsage.UNIFORM);const archivedResources=[];let rp;
  for(const batch of previewBatches(this,states)){for(const snapshot of batch.states){const p=snapshot.preset,live=snapshot.commands??[],mp=this.image(p.mask),gp=this.image(p.texture);let v=this.previews.get(snapshot.id);if(!v){v={id:snapshot.id,preset:p,prefix:this.texture(this.canvas.width,this.canvas.height,'rgba16float'),tail:this.texture(this.canvas.width,this.canvas.height,'rgba16float'),index:-1,keys:new Set,depth:continuous(p)?d.createTexture({size:[this.canvas.width,this.canvas.height],format:'depth24plus',usage:GPUTextureUsage.RENDER_ATTACHMENT}):null,depthFresh:true};this.previews.set(v.id,v);}const published=publishedCommands(snapshot,v);const {stable,prefixKeys,vertexCount,sectors}=livePrefixCommands(v,p,published,this.width,this.height,live);previewDirty(v,stable,live,this.width,this.height,dirty,snapshot.inputTip?.t??snapshot.tip?.t??Infinity);diagnostics.publishedCommands+=stable.length;diagnostics.liveCommands+=live.length;diagnostics.dirtyTiles+=dirty.size;for(const [target,commands,clear]of [[v.prefix,stable,false],[v.tail,live,true]]){const depth=!clear&&v.depth;const descriptor={colorAttachments:[{view:target.createView(),clearValue:{r:0,g:0,b:0,a:0},loadOp:clear?'clear':'load',storeOp:'store'}]};if(depth){descriptor.depthStencilAttachment={view:depth.createView(),depthClearValue:1,depthLoadOp:v.depthFresh?'clear':'load',depthStoreOp:'store'};v.depthFresh=false;}rp=e.beginRenderPass(descriptor);if(commands.length){rp.setPipeline(depth?this.liveDepth:continuous(p)?this.liveSolid:p.__foundation?(p.__foundation.coverageUnion?(commands.every(c=>c[7]===0)?this.foundationSweepPlain:this.foundationSweep):liveAccumulation(p)?this.foundationFlow:this.foundationLive):(liveAccumulation(p)?this.liveFlow:this.live));rp.setBindGroup(0,this.group(this.liveLayout,[uniform(parameters(p,0,0,commands.length,0,this.width,this.height,this.canvas.width,this.canvas.height,false,0,sectors)),this.buffer(pack(commands),GPUBufferUsage.STORAGE),this.image(p.mask),this.image(p.texture)]));const clips=[null];for(const clip of clips){if(clip){if(!clip[2]||!clip[3])continue;rp.setScissorRect(...clip);}rp.setPipeline(depth?this.liveDepth:continuous(p)?this.liveSolid:p.__foundation?(p.__foundation.coverageUnion?(commands.every(c=>c[7]===0)?this.foundationSweepPlain:this.foundationSweep):liveAccumulation(p)?this.foundationFlow:this.foundationLive):(liveAccumulation(p)?this.liveFlow:this.live));rp.draw(clear?6:vertexCount,commands.length);if(depth){rp.setPipeline(this.liveOpaque);rp.draw(clear?6:vertexCount,commands.length);}}}rp.end();}}
  const overlays=[];for(const v of this.previews.values())overlays.push({id:v.id,preset:v.preset,texture:v.prefix},{id:v.id,preset:v.preset,texture:v.tail});const keys=dirty;rp=e.beginRenderPass({colorAttachments:[{view:this.liveTarget.createView(),loadOp:'load',storeOp:'store'}]});rp.setPipeline(this.display);for(const key of keys){const t=this.tiles.get(key),[tx,ty]=key.split(',').map(Number);const params=parameters(t?.preset??emptyPreset,tx*TILE,ty*TILE,0,0,this.width,this.height,this.canvas.width,this.canvas.height);params[24]=t?.active??-1;params[25]=t?.committedId??-1;params[26]=overlays.length;params[28]=this.archiveIds.get(key)??-1;const textures=[];for(let i=0;i<8;i++){textures.push(overlays[i]?.texture??this.zeroLive);params[32+i*4]=overlays[i]?.id??-1;params[33+i*4]=S.blends[overlays[i]?.preset.blend??'normal'];params[34+i*4]=overlays[i]?.preset.__foundation?.opacity??overlays[i]?.preset.opacity??1;params[35+i*4]=overlays[i]?.preset.__foundation?.coverageUnion?3:overlays[i]?.preset.__foundation?.material?2:overlays[i]&&liveAccumulation(overlays[i].preset)?1:0;}const direct=overlays.length===2&&(continuous(overlays[0].preset)||foundationUnion(overlays[0].preset))&&t?.active==null&&!this.archiveIds.has(key)&&overlays[0].id>(t?.committedId??-1);if(direct&&!overlays[0].preset.__foundation)params[34]=1;rp.setPipeline(direct?this.sweepDisplay:this.display);rp.setBindGroup(0,this.group(this.displayLayout,[uniform(params),t?.layer[t.l]??this.zeroLayer,t?.stroke?.[t.s]??this.zeroStroke,...textures,this.archiveTarget]));rp.draw(6);}rp.end();

  if(batch.archive){e.copyTextureToTexture({texture:this.liveTarget},{texture:this.archiveTarget},[this.canvas.width,this.canvas.height]);for(const v of this.previews.values()){this.archivedThrough=Math.max(this.archivedThrough,v.id);for(const key of v.realKeys??[])this.archiveIds.set(key,Math.max(this.archiveIds.get(key)??-1,v.id));archivedResources.push(v.prefix,v.tail);if(v.depth)archivedResources.push(v.depth);}this.previews.clear();}dirty.clear();}
  if(!this.presentationHeld){const presentation=e.beginRenderPass({colorAttachments:[{view:this.context.getCurrentTexture().createView(),clearValue:{r:1,g:1,b:1,a:1},loadOp:'clear',storeOp:'store'}]});presentation.setPipeline(this.present);presentation.setBindGroup(0,d.createBindGroup({layout:this.present.getBindGroupLayout(0),entries:[{binding:0,resource:this.liveTarget.createView()}]}));presentation.draw(3);presentation.end();}
  const retired=[...archivedResources];for(const job of jobs){if(job.skip)continue;this.dirtyConfirmed.add(job.key);const t=this.tile(job.key),solid=continuous(job.preset);if(!job.commit)this.captureBefore(job.id,job.key,t,job.preset,e);if(t.active!==job.id&&!job.commit){if(t.stroke)retired.push(...t.stroke);t.stroke=[this.texture(TILE,TILE,solid?'rgba16float':'rgba32float'),this.texture(TILE,TILE,solid?'rgba16float':'rgba32float')];t.s=0;t.active=job.id;t.preset=job.preset;}if(!t.stroke)throw Error('commit has no stroke');const cb=this.buffer(pack(job.commands.length?job.commands:[new Float32Array(STRIDE)]),GPUBufferUsage.STORAGE);if(solid&&!job.commit){const pass=e.beginRenderPass({colorAttachments:[{view:t.stroke[t.s].createView(),loadOp:'load',storeOp:'store'}]});pass.setPipeline(this.liveSolid);pass.setBindGroup(0,this.group(this.liveLayout,[uniform(parameters(job.preset,t.x,t.y,job.commands.length,2,TILE,TILE,TILE,TILE)),cb,this.image(job.preset.mask),this.image(job.preset.texture)]));pass.draw(6,job.commands.length);pass.end();}else{const gp=this.group(this.depositLayout,[uniform(parameters(job.preset,t.x,t.y,job.commands.length,job.commit?1:0)),t.stroke[t.s],solid?this.zeroStroke:t.stroke[1-t.s],cb,this.image(job.preset.mask),this.image(job.preset.texture),t.layer[t.l],t.layer[1-t.l]]);const cp=e.beginComputePass();cp.setPipeline(job.preset.__foundation?this.foundationDeposit:this.deposit);cp.setBindGroup(0,gp);cp.dispatchWorkgroups(16,16);cp.end();}if(job.commit){t.l=1-t.l;t.committedId=job.id;t.active=null;if((this.archiveIds.get(job.key)??Infinity)<=job.id)this.archiveIds.delete(job.key);retired.push(...t.stroke);t.stroke=null;}else if(!solid)t.s=1-t.s;}
  d.queue.submit([e.finish()]);this.lastSubmission={...diagnostics,cpuSubmitMs:performance.now()-submissionStart};await d.queue.onSubmittedWorkDone();for(const b of this.transient)b.destroy();this.transient=[];for(const t of retired)t.destroy();if(this.error)throw this.error;
 }
 async readViewport(){const d=this.device,w=this.canvas.width,h=this.canvas.height,stride=Math.ceil(w*4/256)*256,b=d.createBuffer({size:stride*h,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ}),e=d.createCommandEncoder();e.copyTextureToBuffer({texture:this.liveTarget},{buffer:b,bytesPerRow:stride},[w,h]);d.queue.submit([e.finish()]);await b.mapAsync(GPUMapMode.READ);const a=new Uint8Array(b.getMappedRange()),out=new Uint8ClampedArray(w*h*4),bgra=this.format.startsWith('bgra');for(let y=0;y<h;y++)for(let x=0;x<w;x++){const src=y*stride+x*4,dst=(y*w+x)*4;out[dst]=a[src+(bgra?2:0)];out[dst+1]=a[src+1];out[dst+2]=a[src+(bgra?0:2)];out[dst+3]=a[src+3];}b.unmap();b.destroy();return out;}
 async read(){const d=this.device,out=new Uint8ClampedArray(this.width*this.height*4);for(const t of this.tiles.values()){const b=d.createBuffer({size:TILE*TILE*4,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});const e=d.createCommandEncoder();e.copyTextureToBuffer({texture:t.layer[t.l]},{buffer:b,bytesPerRow:TILE*4},[TILE,TILE]);d.queue.submit([e.finish()]);await b.mapAsync(GPUMapMode.READ);const a=new Uint8Array(b.getMappedRange());for(let y=0;y<TILE&&t.y+y<this.height;y++){const n=Math.min(TILE,this.width-t.x);out.set(a.subarray(y*TILE*4,(y*TILE+n)*4),((t.y+y)*this.width+t.x)*4);}b.unmap();b.destroy();}return out;}
 retirePreview(id){const v=this.previews.get(id);if(v){for(const key of v.keys)this.dirtyConfirmed.add(key);v.prefix.destroy();v.tail.destroy();v.depth?.destroy();this.previews.delete(id);}}
 invalidateTiles(keys){for(const key of keys){const t=this.tiles.get(key);if(t){for(const s of t.layer)s.destroy();if(t.stroke)for(const s of t.stroke)s.destroy();this.tiles.delete(key);}this.archiveIds.delete(key);this.dirtyConfirmed.add(key);}}
 clear(){for(const id of this.previews.keys())this.retirePreview(id);for(const id of [...this.historyPatches.keys()])this.historyRelease(id);for(const t of this.tiles.values()){for(const s of t.layer)s.destroy();if(t.stroke)for(const s of t.stroke)s.destroy();}this.tiles.clear();this.dirtyConfirmed.clear();this.archiveIds.clear();this.archivedThrough=-1;const e=this.device.createCommandEncoder(),p=e.beginRenderPass({colorAttachments:[{view:this.liveTarget.createView(),clearValue:{r:0,g:0,b:0,a:0},loadOp:'clear',storeOp:'store'}]});p.end();this.device.queue.submit([e.finish()]);}
 destroy(){this.clear();for(const t of this.images.values())t.destroy();this.liveTarget.destroy();this.archiveTarget.destroy();this.zeroLive.destroy();this.zeroStroke.destroy();this.zeroLayer.destroy();this.context.unconfigure();this.device.destroy();}
}
