import test from 'node:test';import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {referenceBrushes,createPreset,compilePreset,evaluateDynamics,exportPresets,importPresets,PresetState,cursorState,correctGeometry,geometryContext,predictFoundation,interpolateAngle} from '../dist/rt/foundation.mjs';
import {CanonicalBuilder,validateRecord,cpuReference,continuous,liveAccumulation} from '../dist/rt/model.mjs';
import {sweepPrefixCommands,GpuRenderer,TileDocument} from '../dist/rt/renderer.mjs';
const point=(x,t,p=.7)=>({x,y:30,t,pressure:p,pointerType:'pen',origin:'coalesced',tilt:.3,azimuth:.4,twist:.5});
test('wide constant sweep feedback uses bounded strips/joins without mutating canonical paint or dropping endpoint caps',()=>{const p=structuredClone(referenceBrushes[6]);p.size=512;const b=new CanonicalBuilder(p);for(let i=0;i<16;i++)b.accept({...point(20+i*10,i*5),y:30+i*i});const canonical=b.commands.map(c=>Array.from(c));const v={};const out=sweepPrefixCommands(v,b.p,b.commands.slice(0,-1),b.commands.slice(-1));assert.ok(out.stable.some(c=>c[23]===-2));assert.equal(out.stable[0][23],b.commands[0][23]);assert.deepEqual(b.commands.map(c=>Array.from(c)),canonical);const end=sweepPrefixCommands(v,b.p,b.commands.slice(-1),[]);assert.ok(end.stable.every(c=>c[23]!==-2));const textured={...b.p,__foundation:{...b.p.__foundation,texture:{...b.p.__foundation.texture,followDirection:true}}};assert.ok(sweepPrefixCommands({},textured,b.commands,[]).stable.every(c=>c[23]!==-2));});
test('saved version-three strokes from the pre-sweep implementation retain all seven brush results',()=>{const fixture=JSON.parse(readFileSync(new URL('./fixtures/pre-sweep-foundation-v3.json',import.meta.url),'utf8'));assert.equal(fixture.source,'b18e2b0d66906454cc95aa9d8b2319cb053897f1');assert.equal(fixture.records.length,7);for(const record of fixture.records)assert.deepEqual(validateRecord(record),record);});
function stroke(p,samples,seed=[12,34],context={}){const b=new CanonicalBuilder(p,seed,0,context);for(const s of samples)b.accept(s);b.finish();return b.record();}
test('seven reference brushes replay actual sensors, pressure and material settings',()=>{for(const p of referenceBrushes){const r=stroke(p,Array.from({length:30},(_,i)=>point(20+i,i*1000/240,i<10?.1:i<20?.9:.05)));assert.deepEqual(validateRecord(r),r);assert.equal(r.raw.length,30);assert.equal(r.version,3);assert.equal(r.geometry[1].origin,'coalesced');assert.ok(Number.isFinite(r.geometry[1].velocity));assert.ok(r.commands.length);}});
test('finish never moves, extends, thins or changes already published foundation commands',()=>{for(const p of referenceBrushes)for(const n of [1,2,3,40]){const b=new CanonicalBuilder(p);for(let i=0;i<n;i++)b.accept(point(20+i*.5,i*5,.2));const live=[];live.push(...b.ready());const before=b.commands.map(c=>Array.from(c));const tail=b.commands.slice(b.published).map(c=>Array.from(c));const finalized=b.finish();assert.deepEqual(finalized.map(c=>Array.from(c)),tail);assert.deepEqual(b.record().commands,before);assert.equal(live.length+tail.length,before.length);}});
test('device curve then brush curve, pressure smoothing separate from constant-velocity position',()=>{const p=createPreset('pressure','pressure',{pressure:{deviceCurve:[[0,0],[1,.5]],curve:[[0,0],[.5,.25],[1,1]],smoothing:0},dynamics:[{source:'pressure',target:'size',mode:'multiply',min:0,max:1,curve:[[0,0],[1,1]]}]});const r=stroke(p,[point(20,0,1),point(30,5,1)]);assert.equal(r.geometry[0].p,.25);assert.equal(r.commands[0][2],4);assert.equal(r.geometry[1].x,30);});
test('mapping sources, ordered multiply/add/replace, input range, missing sensor fallback',()=>{const p=createPreset('mapping','mapping',{renderer:'stamp',dynamics:[{source:'velocity',target:'size',mode:'multiply',min:.5,max:1,curve:[[0,0],[1,1]],input:[0,100]},{source:'random',target:'rotation',mode:'add',min:0,max:1,curve:[[0,0],[1,1]]},{source:'twist',target:'aspect',mode:'replace',min:.2,max:.8,curve:[[0,0],[1,1]],fallback:.5}]});const rp=compilePreset(p),q={x:0,y:0,t:0,p:1,valid:0,tilt:0,azimuth:0,twist:0};const a=evaluateDynamics(q,rp,0,[1,2],0,50,0,0),b=evaluateDynamics(q,rp,0,[1,2],0,50,0,0);assert.equal(a.size,12);assert.equal(a.aspect,.5);assert.deepEqual(a,b);});
test('pressure curves produce variable G-pen and constant technical pen through same pipeline',()=>{const samples=[point(0,0,.05),point(20,5,1)];const g=stroke(referenceBrushes[0],samples),technical=stroke(referenceBrushes[2],samples);assert.ok(g.commands[1][2]>g.commands[0][2]);assert.equal(technical.commands[0][2],technical.commands[1][2]);assert.ok(continuous(g.preset));assert.ok(compilePreset(referenceBrushes[4]).__foundation.coverageUnion);assert.equal(liveAccumulation(compilePreset(referenceBrushes[4])),false);});
test('absolute spacing is independent of pressure-driven particle diameter',()=>{const p=createPreset('spacing','spacing',{renderer:'stamp',spacing:{unit:'absolute',value:3},dynamics:[{source:'pressure',target:'size',mode:'multiply',min:.1,max:1,curve:[[0,0],[1,1]]}]});const r=stroke(p,[point(0,0,.1),point(30,20,1)]);assert.deepEqual(r.commands.map(c=>c[0]),Array.from({length:11},(_,i)=>i*3));});
test('scatter density, disk bias, color/random/texture repeat exactly with seed',()=>{const p=createPreset('scatter','scatter',{renderer:'stamp',scatter:{enabled:true,density:6,radius:.5,particleSize:.2,bias:.6,rotation:'center'},random:[{target:'hue',amount:.2},{target:'size',amount:.3},{target:'spacing',amount:.1}],texture:{paper:{strength:.5,invert:true,minimum:.2}}});const samples=[point(20,0),point(40,20)];const a=stroke(p,samples),b=stroke(p,samples),c=stroke(p,samples,[12,35]);assert.deepEqual(a,b);assert.notDeepEqual(a.commands,c.commands);assert.deepEqual(cpuReference(a,80,60),cpuReference(b,80,60));assert.ok(a.commands.length>=6);});
test('preset pack preserves embedded resources and rejects unsupported versions/missing resources',()=>{const p=createPreset('mask','mask',{renderer:'stamp',tip:{shape:'mask',resource:'shape'},resources:{shape:{kind:'mask',width:2,height:2,alpha:[0,1,1,0]}}});const pack=exportPresets([p]);assert.deepEqual(importPresets(pack),[p]);assert.equal(compilePreset(p).mask.alpha[1],1);assert.throws(()=>compilePreset({...p,resources:{}}),/missing/);assert.throws(()=>importPresets(pack.replace('"version": 1','"version": 99')),/version|pack/);});
test('prediction rejects turns, deceleration, idle and release, never enters canonical journal',()=>{const p=createPreset('prediction','prediction',{prediction:{enabled:true}}),rp=compilePreset(p);const points=[0,1,2].map(i=>({x:i*5,y:0,t:i*5,p:.8,valid:1}));const next=predictFoundation(points,10,[],rp);assert.ok(next?.predicted);assert.ok(next.x<=13);assert.equal(predictFoundation([...points.slice(0,2),{...points[2],x:5,y:5}],10,[],rp),null);assert.equal(predictFoundation([...points.slice(0,2),{...points[2],x:6}],10,[],rp),null);assert.equal(predictFoundation(points,50,[],rp),null);assert.equal(predictFoundation([...points.slice(0,2),{...points[2],p:.01}],10,[],rp),null);assert.throws(()=>new CanonicalBuilder(p).accept(next),/prediction/);});
test('known geometry end envelope is evaluated before drawing; freehand cannot use unknown future',()=>{const p=createPreset('shape','shape',{taper:{size:{end:{mode:'known',length:10,minimum:.05}}}}),samples=[point(0,0,1),point(10,5,1),point(20,10,1)];assert.throws(()=>new CanonicalBuilder(p),/known endpoint/);const r=stroke(p,samples,[12,34],geometryContext(samples));assert.equal(r.commands.at(-1)[2],.8);assert.deepEqual(validateRecord(r),r);});
test('tap and repeated short strokes survive with canonical data intact',()=>{for(let i=0;i<200;i++){const r=stroke(referenceBrushes[i%7],[point(30,i*10,.7)]);assert.equal(r.raw.length,1);assert.ok(r.commands.length>=1);assert.deepEqual(validateRecord(r),r);}});
test('strong constant/fast stabilization stays bounded and exact on straight constant velocity',()=>{for(const mode of ['increase','reduce']){const p=createPreset('stabilize','stabilize',{stabilization:{constant:1,fast:1,speedMode:mode}});const r=stroke(p,Array.from({length:2400},(_,i)=>point(i*.5,i*1000/240)));assert.equal(r.raw.length,2400);for(let i=0;i<r.geometry.length;i++)assert.ok(Math.abs(r.geometry[i].x-r.raw[i].x)<1e-8);}});
test('temporary brush locks do not mutate saved data; cursor reads current sensor state',()=>{const state=new PresetState(referenceBrushes);state.select(referenceBrushes[0].id,'per-brush');state.override({size:40});assert.equal(state.current().size,40);assert.equal(state.saved.get(referenceBrushes[0].id).size,16);state.select(referenceBrushes[1].id,'per-brush');state.select(referenceBrushes[0].id,'per-brush');assert.equal(state.current().size,40);state.select(referenceBrushes[0].id,'restore');assert.equal(state.current().size,16);const cursor=cursorState(referenceBrushes[0],point(0,0,1));assert.equal(cursor.shape,'round');assert.equal(cursor.barrelRoll,.5);assert.ok(cursor.size>0);});
test('post correction is explicit, bounded and preserves endpoints; unsupported simulations fail clearly',()=>{const samples=[point(0,0),{...point(10,5),y:50},point(20,10)],corrected=correctGeometry(samples,1);assert.deepEqual(corrected[0],samples[0]);assert.deepEqual(corrected.at(-1),samples.at(-1));assert.ok(Math.hypot(corrected[1].x-samples[1].x,corrected[1].y-samples[1].y)<=1);assert.throws(()=>compilePreset(createPreset('wet','wet',{kind:'watercolor',renderer:'wet-1'})),/extension required/);assert.throws(()=>compilePreset(createPreset('post','post',{stabilization:{post:1}})),/explicit/);});
test('corrupted new record cannot replace saved material, geometry or random sequence',()=>{const r=stroke(referenceBrushes[4],[point(20,0),point(30,10)]);r.commands[0][5]=.99;assert.throws(()=>validateRecord(r),/replay mismatch/);});

test('barrel/azimuth wrap uses the shortest angular arc, release is retained without paint',()=>{const mid=interpolateAngle(6.2,.1,.5);assert.ok(Math.abs(mid-Math.PI*2)<.1);const b=new CanonicalBuilder(referenceBrushes[0]);b.accept(point(20,0));const before=b.commands.map(c=>Array.from(c));b.release({...point(300,5,0),origin:'release'});b.finish();const r=b.record();assert.deepEqual(r.commands,before);assert.equal(r.releaseInput.x,300);assert.equal(r.raw.length,1);assert.deepEqual(validateRecord(r),r);});

test('marker cap applies opacity once; build-up and flow limits select the material path',()=>{const marker=stroke(referenceBrushes[3],[point(30,0),point(40,5)]);const image=cpuReference(marker,80,60);assert.equal(image[(30*80+35)*4+3],Math.round(.45*255));assert.equal(marker.preset.__foundation.opacity,1);const paint=createPreset('build','build',{paint:'build-up',opacity:.2});assert.equal(continuous(compilePreset(paint)),false);const limited=createPreset('limited','limited',{limits:{flow:[0,.5]}});assert.equal(continuous(compilePreset(limited)),false);});

test('cursor matches pressure fallback, mapped color and build-up opacity without double multiplication',()=>{const p=createPreset('cursor','cursor',{renderer:'stamp',paint:'build-up',opacity:.4,color:[1,0,0],pressure:{fallback:.25,smoothing:0},dynamics:[{source:'pressure',target:'size',mode:'multiply',min:0,max:1,curve:[[0,0],[1,1]]},{source:'pressure',target:'hue',mode:'replace',min:1/3,max:1/3,curve:[[0,0],[1,1]]}]});const s={x:30,y:30,t:0,pointerType:'mouse'},cursor=cursorState(p,s),r=stroke(p,[s]);assert.equal(cursor.size,r.commands[0][2]);assert.deepEqual(cursor.color,r.commands[0].slice(8,11));assert.equal(cursor.opacity,.4);assert.equal(cursor.color[1],1);});

test('predicted release metadata is rejected just like predicted paint input',()=>{const b=new CanonicalBuilder(referenceBrushes[0]);b.accept(point(20,0));assert.throws(()=>b.release({...point(20,5,0),origin:'predicted'}),/prediction/);assert.throws(()=>b.release({...point(20,5,0),predicted:true}),/predict/);});

test('swept pencil and soft erase always publish the latest contact, independent of spacing',()=>{for(const source of [referenceBrushes[4],referenceBrushes[6]]){const p=structuredClone(source);p.size=1024;const b=new CanonicalBuilder(p);for(let i=0;i<480;i++)b.accept(point(100+i*.1,i*1000/240));assert.ok(b.commands.length>0&&b.commands.length<=480);assert.equal(b.commands.at(-1)[20],b.geometry.at(-1).t);assert.equal(b.commands.at(-1)[0],b.geometry.at(-1).x);const before=b.commands.map(c=>Array.from(c));b.finish();assert.deepEqual(b.record().commands,before);}});

test('pending sweep input is displayed on completion with one submission and intact formal geometry',async()=>{
 const p=compilePreset(referenceBrushes[6]),document=new TileDocument(256,256),builder=new CanonicalBuilder(referenceBrushes[6]);
 for(let i=0;i<8;i++)builder.accept({...point(20+i*10,i*5),y:30+(i%2)*10});builder.finish();assert.ok(builder.commands.length>=3);
 document.append(1,p,builder.commands);const retained=document.count,seen=[],pending=[];let inFlight=0,maxInFlight=0;
 const backend={immediatePreview:true,render(snapshot,jobs){inFlight++;maxInFlight=Math.max(maxInFlight,inFlight);seen.push({end:snapshot.stableEnd,jobs:jobs.length});return new Promise(resolve=>pending.push(()=>{inFlight--;resolve();}));},destroy(){}};
 const renderer=new GpuRenderer(backend,256,256),source=builder.commands;renderer.document=document;
 const send=end=>renderer.setLive({id:1,preset:p,stableSource:source,stableEnd:end,commands:[],tip:{x:30,y:30,t:performance.now()},finished:false});
 send(1);renderer.frame(performance.now());send(2);send(3);assert.equal(seen.length,1);
 pending.shift()();await new Promise(resolve=>setImmediate(resolve));
 assert.deepEqual(seen,[{end:1,jobs:0},{end:3,jobs:0}]);assert.equal(maxInFlight,1);assert.equal(document.count,retained);
 pending.shift()();await new Promise(resolve=>setImmediate(resolve));assert.equal(seen.length,2);assert.ok(document.jobs.length>0);renderer.destroy();
});
