import test from 'node:test';import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {referenceBrushes,createPreset,compilePreset,evaluateDynamics,exportPresets,importPresets,PresetState,cursorState,correctGeometry,geometryContext,predictFoundation,interpolateAngle} from '../dist/rt/foundation.mjs';
import {CanonicalBuilder,validateRecord,cpuReference,continuous,liveAccumulation,forceFadePreviewCommands,forceFadeLengths} from '../dist/rt/model.mjs';
import {sweepPrefixCommands,GpuRenderer,TileDocument,previewBatches} from '../dist/rt/renderer.mjs';
import {RealtimeSession} from '../dist/rt/session.mjs';
const point=(x,t,p=.7)=>({x,y:30,t,pressure:p,pointerType:'pen',origin:'coalesced',tilt:.3,azimuth:.4,twist:.5});
test('wide constant sweep feedback uses bounded strips/joins without mutating canonical paint or dropping endpoint caps',()=>{const p=structuredClone(referenceBrushes[6]);p.size=512;const b=new CanonicalBuilder(p);for(let i=0;i<16;i++)b.accept({...point(20+i*10,i*5),y:30+i*i});const canonical=b.commands.map(c=>Array.from(c));const v={};const out=sweepPrefixCommands(v,b.p,b.commands.slice(0,-1),b.commands.slice(-1));assert.ok(out.stable.some(c=>c[23]===-2));assert.equal(out.stable[0][23],b.commands[0][23]);assert.deepEqual(b.commands.map(c=>Array.from(c)),canonical);const end=sweepPrefixCommands(v,b.p,b.commands.slice(-1),[]);assert.ok(end.stable.every(c=>c[23]!==-2));const textured={...b.p,__foundation:{...b.p.__foundation,texture:{...b.p.__foundation.texture,followDirection:true}}};assert.ok(sweepPrefixCommands({},textured,b.commands,[]).stable.every(c=>c[23]!==-2));});
test('saved version-three strokes from the pre-sweep implementation retain all seven brush results',()=>{const fixture=JSON.parse(readFileSync(new URL('./fixtures/pre-sweep-foundation-v3.json',import.meta.url),'utf8'));assert.equal(fixture.source,'b18e2b0d66906454cc95aa9d8b2319cb053897f1');assert.equal(fixture.records.length,7);for(const record of fixture.records)assert.deepEqual(validateRecord(record),record);});
function stroke(p,samples,seed=[12,34],context={}){const b=new CanonicalBuilder(p,seed,0,context);for(const s of samples)b.accept(s);b.finish();return b.record();}
test('seven reference brushes replay actual sensors, pressure and material settings',()=>{for(const p of referenceBrushes){const r=stroke(p,Array.from({length:30},(_,i)=>point(20+i,i*1000/240,i<10?.1:i<20?.9:.05)));assert.deepEqual(validateRecord(r),r);assert.equal(r.raw.length,30);assert.equal(r.version,3);assert.equal(r.geometry[1].origin,'coalesced');assert.ok(Number.isFinite(r.geometry[1].velocity));assert.ok(r.commands.length);}});
test('finish preserves live geometry until release; force fade may then rewrite the G-pen stroke',()=>{for(const p of referenceBrushes)for(const n of [1,2,3,40]){const b=new CanonicalBuilder(p);for(let i=0;i<n;i++)b.accept(point(20+i*.5,i*5,.2));const live=b.ready(),published=b.published,before=b.commands.map(c=>Array.from(c)),finalized=b.finish().map(c=>Array.from(c)),record=b.record();assert.equal(live.length,published);assert.equal(finalized.length,before.length-published);if(p.id==='foundation-g-pen'&&b.distance>.5){assert.equal(record.commands.length,before.length);assert.ok(record.commands.some((c,i)=>Math.abs(c[2]-before[i][2])>1e-9));assert.equal(record.commands.at(-1)[0],before.at(-1)[0]);assert.equal(record.commands.at(-1)[1],before.at(-1)[1]);}else{assert.deepEqual(record.commands,before);}}});
test('device curve then brush curve, pressure smoothing separate from constant-velocity position',()=>{const p=createPreset('pressure','pressure',{pressure:{deviceCurve:[[0,0],[1,.5]],curve:[[0,0],[.5,.25],[1,1]],smoothing:0},dynamics:[{source:'pressure',target:'size',mode:'multiply',min:0,max:1,curve:[[0,0],[1,1]]}]});const r=stroke(p,[point(20,0,1),point(30,5,1)]);assert.equal(r.geometry[0].p,.25);assert.equal(r.commands[0][2],4);assert.equal(r.geometry[1].x,30);});
test('mapping sources, ordered multiply/add/replace, input range, missing sensor fallback',()=>{const p=createPreset('mapping','mapping',{renderer:'stamp',dynamics:[{source:'velocity',target:'size',mode:'multiply',min:.5,max:1,curve:[[0,0],[1,1]],input:[0,100]},{source:'random',target:'rotation',mode:'add',min:0,max:1,curve:[[0,0],[1,1]]},{source:'twist',target:'aspect',mode:'replace',min:.2,max:.8,curve:[[0,0],[1,1]],fallback:.5}]});const rp=compilePreset(p),q={x:0,y:0,t:0,p:1,valid:0,tilt:0,azimuth:0,twist:0};const a=evaluateDynamics(q,rp,0,[1,2],0,50,0,0),b=evaluateDynamics(q,rp,0,[1,2],0,50,0,0);assert.equal(a.size,12);assert.equal(a.aspect,.5);assert.deepEqual(a,b);});
test('ordinary G-pen pressure remains variable when forced in-out is OFF',()=>{const samples=[point(0,0,.05),point(20,5,1)],gp=structuredClone(referenceBrushes[0]);gp.forceFade={...gp.forceFade,enabled:false};gp.taper.size.start.mode='none';const g=stroke(gp,samples),technical=stroke(referenceBrushes[2],samples);assert.ok(g.commands[1][2]>g.commands[0][2]);assert.equal(technical.commands[0][2],technical.commands[1][2]);assert.ok(continuous(g.preset));assert.ok(compilePreset(referenceBrushes[4]).__foundation.coverageUnion);assert.equal(liveAccumulation(compilePreset(referenceBrushes[4])),false);});
test('G-pen forced in-out uses adaptive path-length reach after finish',()=>{const p=structuredClone(referenceBrushes[0]);p.size=30;p.forceFade={...p.forceFade,start:0,end:1};const b=new CanonicalBuilder(p);for(let i=0;i<=20;i++)b.accept(point(i*5,i*5,.8));const before=b.commands.map(c=>Array.from(c));b.finish();const r=b.record();assert.equal(before.length,r.commands.length);assert.deepEqual(before.map(c=>[c[0],c[1]]),r.commands.map(c=>[c[0],c[1]]));assert.ok(Math.abs(r.commands[0][2]-30)<1e-9);assert.ok(r.commands[Math.floor(r.commands.length/2)][2]<30);assert.ok(r.commands.at(-1)[2]<3);});
test('force fade preserves short and medium percentage reach, then soft-limits only extreme strokes',()=>{const f={start:.4,end:.4};const short=forceFadeLengths(f,40),medium=forceFadeLengths(f,500),long=forceFadeLengths(f,5000);assert.ok(short.end>15.99&&short.end<=16);assert.ok(medium.end>190&&medium.end<200);assert.ok(long.end>700&&long.end<781);assert.ok(long.end>medium.end*3.5);const subtle=forceFadeLengths({start:0,end:.12},10000),strong=forceFadeLengths({start:0,end:1},10000);assert.ok(subtle.end<600);assert.ok(strong.end>1100&&strong.end<1201);const both=forceFadeLengths({start:1,end:1},40);assert.ok(Math.abs(both.start+both.end-40)<1e-9);assert.ok(Math.abs(both.start-both.end)<1e-9);});
test('forced fade tail keeps its configured reach but stays fuller before the terminal tip',()=>{const p=structuredClone(referenceBrushes[0]);p.size=20;p.stabilization.constant=0;p.stabilization.fast=0;p.pressure.smoothing=0;p.taper.size.start.mode='none';p.forceFade={...p.forceFade,enabled:true,start:0,end:.4};const samples=Array.from({length:51},(_,i)=>point(i*10,i*5,.8)),r=stroke(p,samples),total=r.commands.at(-1)[21],tail=forceFadeLengths(p.forceFade,total).end,nearest=ratio=>r.commands.reduce((best,c)=>Math.abs((total-c[21])-tail*ratio)<Math.abs((total-best[21])-tail*ratio)?c:best,r.commands[0]),early=nearest(.75),late=nearest(.2);assert.ok(tail>190&&tail<200);assert.ok(early[2]>20*.78,'tail became visibly thin too early');assert.ok(late[2]<20*.35,'terminal tail did not narrow enough');assert.ok(r.commands.at(-1)[2]<1);});
test('very long forced fade keeps a full-width middle while retaining a long tapered tail',()=>{const p=structuredClone(referenceBrushes[0]);p.size=20;p.stabilization.constant=0;p.stabilization.fast=0;p.pressure.smoothing=0;p.taper.size.start.mode='none';p.forceFade={...p.forceFade,enabled:true,start:0,end:1};const samples=Array.from({length:61},(_,i)=>point(i*50,i*5,.8)),r=stroke(p,samples);const at1500=r.commands.find(c=>Math.abs(c[21]-1500)<1e-9),at2500=r.commands.find(c=>Math.abs(c[21]-2500)<1e-9),at2900=r.commands.find(c=>Math.abs(c[21]-2900)<1e-9);assert.ok(at1500&&Math.abs(at1500[2]-20)<1e-9);assert.ok(at2500&&at2500[2]<20&&at2500[2]>at2900[2]);assert.ok(at2900&&at2900[2]<20);assert.ok(r.commands.at(-1)[2]<1);});
test('G-pen force fade can affect both ends after release and does not erase a tap',()=>{const p=structuredClone(referenceBrushes[0]);p.taper.size.start.mode='none';p.forceFade={...p.forceFade,start:.5,end:.5};const b=new CanonicalBuilder(p);for(let i=0;i<=20;i++)b.accept(point(i*5,i*5,.8));const before=b.commands.map(c=>Array.from(c));b.finish();const r=b.record();assert.ok(r.commands[0][2]<before[0][2]);assert.ok(r.commands.at(-1)[2]<before.at(-1)[2]);const tap=new CanonicalBuilder(p);tap.accept(point(20,0,.8));const tapBefore=tap.commands.map(c=>Array.from(c));tap.finish();assert.deepEqual(tap.record().commands,tapBefore);});
test('forced in-out ON rebuilds final width from brush size and path only',()=>{const base=structuredClone(referenceBrushes[0]);base.size=20;base.stabilization.constant=0;base.stabilization.fast=0;base.pressure.smoothing=0;base.forceFade={...base.forceFade,enabled:true,start:.25,end:.75};base.taper.size.start={...base.taper.size.start,mode:'ramp',length:500,minimum:.01};const make=(pressure,dt)=>{const p=structuredClone(base),b=new CanonicalBuilder(p);for(let i=0;i<=30;i++)b.accept(point(i*4,i*dt,pressure));const raw=b.commands.map(c=>Array.from(c)),preview=forceFadePreviewCommands(raw,b.p).map(c=>Array.from(c));b.finish();return {raw,preview,final:b.record().commands};};const low=make(.05,4),high=make(1,4),slow=make(.6,80);assert.ok(low.raw.some((c,i)=>Math.abs(c[2]-high.raw[i][2])>.1));for(const result of [low,high,slow])assert.ok(result.preview.every(c=>Math.abs(c[2]-20)<1e-9&&Math.abs(c[18]-10)<1e-9));assert.deepEqual(low.final.map(c=>[c[0],c[1],c[2],c[18]]),high.final.map(c=>[c[0],c[1],c[2],c[18]]));assert.deepEqual(high.final.map(c=>[c[0],c[1],c[2],c[18]]),slow.final.map(c=>[c[0],c[1],c[2],c[18]]));assert.ok(high.final.at(-1)[2]<2);});
test('forced in-out OFF performs no pen-up rewrite',()=>{const p=structuredClone(referenceBrushes[0]);p.taper.size.start.mode='none';p.forceFade={...p.forceFade,enabled:false,start:1,end:1};const b=new CanonicalBuilder(p);for(let i=0;i<=24;i++)b.accept(point(i*4,i*8,.8));const before=b.commands.map(c=>Array.from(c));b.finish();assert.deepEqual(b.record().commands,before);});
test('forced in-out is independent of drawing speed for the same path and pressure',()=>{const p=structuredClone(referenceBrushes[0]);p.taper.size.start.mode='none';p.stabilization.constant=0;p.stabilization.fast=0;p.pressure.smoothing=0;p.forceFade={...p.forceFade,start:.25,end:.75};const make=dt=>{const b=new CanonicalBuilder(p);for(let i=0;i<=24;i++)b.accept(point(i*4,i*dt,.8));const live=b.commands.map(c=>Array.from(c));b.finish();return {live,final:b.record().commands};};const fast=make(2),slow=make(80);assert.deepEqual(fast.live.map(c=>[c[0],c[1],c[2]]),slow.live.map(c=>[c[0],c[1],c[2]]));assert.deepEqual(fast.final.map(c=>[c[0],c[1],c[2]]),slow.final.map(c=>[c[0],c[1],c[2]]));assert.ok(fast.final.at(-1)[2]<fast.live.at(-1)[2]);});
test('forced in-out ignores ordinary taper and scales from selected brush size',()=>{const samples=Array.from({length:31},(_,i)=>point(i*4,i*8,.55));const make=(size,ordinary)=>{const p=structuredClone(referenceBrushes[0]);p.size=size;p.stabilization.constant=0;p.stabilization.fast=0;p.pressure.smoothing=0;p.forceFade={...p.forceFade,enabled:true,start:.35,end:.65};if(ordinary){p.taper.size.start={...p.taper.size.start,mode:'ramp',unit:'distance',length:1000,minimum:.01};p.taper.size.end={...p.taper.size.end,mode:'release',unit:'distance',length:1000,minimum:2};}else{p.taper.size.start={...p.taper.size.start,mode:'none'};p.taper.size.end={...p.taper.size.end,mode:'none'};}return stroke(p,samples).commands;};const plain20=make(20,false),extreme20=make(20,true),plain30=make(30,false);assert.deepEqual(extreme20.map(c=>[c[0],c[1],c[2],c[18]]),plain20.map(c=>[c[0],c[1],c[2],c[18]]));assert.equal(plain20.length,plain30.length);for(let i=0;i<plain20.length;i++){assert.ok(Math.abs(plain30[i][2]-plain20[i][2]*1.5)<1e-9);assert.ok(Math.abs(plain30[i][18]-plain20[i][18]*1.5)<1e-9);}});
test('G-pen limits abrupt diameter jumps before forced fade finalization',()=>{const p=structuredClone(referenceBrushes[0]);p.size=30;const b=new CanonicalBuilder(p);for(let i=0;i<40;i++)b.accept(point(i,i*5,i%2?.98:.3));for(let i=1;i<b.commands.length;i++){const travel=Math.max(.25,b.commands[i][21]-b.commands[i-1][21]);assert.ok(Math.abs(b.commands[i][2]-b.commands[i-1][2])<=p.pressure.sizeSlope*travel+1e-9);}});
test('legacy version-two presets without forceFade remain structurally unchanged when compiled',()=>{const p=createPreset('legacy-shape','legacy-shape');delete p.forceFade;const rp=compilePreset(p);assert.equal(Object.hasOwn(rp.__foundation.preset,'forceFade'),false);assert.deepEqual(rp.__foundation.preset,p);});
test('brush start/end thickness ratios accept ibis-style values through 200 percent',()=>{const p=createPreset('thick-start','thick-start',{taper:{size:{start:{mode:'ramp',unit:'distance',length:10,minimum:2,curve:[[0,0],[1,1]]}}}});assert.equal(compilePreset(p).__foundation.preset.taper.size.start.minimum,2);});
test('pencil pressure changes deposit flow and grain instead of whole-stroke opacity',()=>{const p=referenceBrushes[4],rp=compilePreset(p),low=evaluateDynamics({x:0,y:0,t:0,p:.05,valid:1,tilt:0,azimuth:0,twist:0},rp,0,[1,2],0,0,0,0),high=evaluateDynamics({x:0,y:0,t:0,p:1,valid:1,tilt:0,azimuth:0,twist:0},rp,0,[1,2],0,0,0,0);assert.equal(p.dynamics.some(m=>m.target==='opacity'),false);assert.ok(p.dynamics.some(m=>m.target==='flow'));assert.ok(p.dynamics.some(m=>m.target==='grain'));assert.equal(p.texture.paper.kind,'noise');assert.equal(low.opacity,high.opacity);assert.ok(low.flow<high.flow);assert.ok(low.grain>high.grain);});
test('reference brushes carry purpose-specific editable thickness ranges without clamping pressure dynamics',()=>{const expected=[[.75,30],[.3,60],[.3,60],[1,500],[.3,120],[1,1000],[1,1000]];assert.deepEqual(referenceBrushes.map(p=>p.uiSizeRange),expected);assert.deepEqual(referenceBrushes[0].limits.size,[.75,4096]);for(const p of referenceBrushes.slice(1))assert.deepEqual(p.limits.size,[.01,4096]);});
test('absolute spacing is independent of pressure-driven particle diameter',()=>{const p=createPreset('spacing','spacing',{renderer:'stamp',spacing:{unit:'absolute',value:3},dynamics:[{source:'pressure',target:'size',mode:'multiply',min:.1,max:1,curve:[[0,0],[1,1]]}]});const r=stroke(p,[point(0,0,.1),point(30,20,1)]);assert.deepEqual(r.commands.map(c=>c[0]),Array.from({length:11},(_,i)=>i*3));});
test('scatter density, disk bias, color/random/texture repeat exactly with seed',()=>{const p=createPreset('scatter','scatter',{renderer:'stamp',scatter:{enabled:true,density:6,radius:.5,particleSize:.2,bias:.6,rotation:'center'},random:[{target:'hue',amount:.2},{target:'size',amount:.3},{target:'spacing',amount:.1}],texture:{paper:{strength:.5,invert:true,minimum:.2}}});const samples=[point(20,0),point(40,20)];const a=stroke(p,samples),b=stroke(p,samples),c=stroke(p,samples,[12,35]);assert.deepEqual(a,b);assert.notDeepEqual(a.commands,c.commands);assert.deepEqual(cpuReference(a,80,60),cpuReference(b,80,60));assert.ok(a.commands.length>=6);});
test('preset pack preserves embedded resources and rejects unsupported versions/missing resources',()=>{const p=createPreset('mask','mask',{renderer:'stamp',tip:{shape:'mask',resource:'shape'},resources:{shape:{kind:'mask',width:2,height:2,alpha:[0,1,1,0]}}});const pack=exportPresets([p]);assert.deepEqual(importPresets(pack),[p]);assert.equal(compilePreset(p).mask.alpha[1],1);assert.throws(()=>compilePreset({...p,resources:{}}),/missing/);assert.throws(()=>importPresets(pack.replace('"version": 1','"version": 99')),/version|pack/);});
test('prediction rejects turns, deceleration, idle and release, never enters canonical journal',()=>{const p=createPreset('prediction','prediction',{prediction:{enabled:true}}),rp=compilePreset(p);const points=[0,1,2].map(i=>({x:i*5,y:0,t:i*5,p:.8,valid:1}));const next=predictFoundation(points,10,[],rp);assert.ok(next?.predicted);assert.ok(next.x<=13);assert.equal(predictFoundation([...points.slice(0,2),{...points[2],x:5,y:5}],10,[],rp),null);assert.equal(predictFoundation([...points.slice(0,2),{...points[2],x:6}],10,[],rp),null);assert.equal(predictFoundation(points,50,[],rp),null);assert.equal(predictFoundation([...points.slice(0,2),{...points[2],p:.01}],10,[],rp),null);assert.throws(()=>new CanonicalBuilder(p).accept(next),/prediction/);});
test('known geometry end envelope is evaluated before drawing; freehand cannot use unknown future',()=>{const p=createPreset('shape','shape',{taper:{size:{end:{mode:'known',length:10,minimum:.05}}}}),samples=[point(0,0,1),point(10,5,1),point(20,10,1)];assert.throws(()=>new CanonicalBuilder(p),/known endpoint/);const r=stroke(p,samples,[12,34],geometryContext(samples));assert.equal(r.commands.at(-1)[2],.8);assert.deepEqual(validateRecord(r),r);});
test('tap and repeated short strokes survive with canonical data intact',()=>{for(let i=0;i<200;i++){const r=stroke(referenceBrushes[i%7],[point(30,i*10,.7)]);assert.equal(r.raw.length,1);assert.ok(r.commands.length>=1);assert.deepEqual(validateRecord(r),r);}});
test('strong constant/fast stabilization stays bounded and exact on straight constant velocity',()=>{for(const mode of ['increase','reduce']){const p=createPreset('stabilize','stabilize',{stabilization:{constant:1,fast:1,speedMode:mode}});const r=stroke(p,Array.from({length:2400},(_,i)=>point(i*.5,i*1000/240)));assert.equal(r.raw.length,2400);for(let i=0;i<r.geometry.length;i++)assert.ok(Math.abs(r.geometry[i].x-r.raw[i].x)<1e-8);}});
test('temporary brush locks do not mutate saved data; cursor reads current sensor state',()=>{const state=new PresetState(referenceBrushes);state.select(referenceBrushes[0].id,'per-brush');state.override({size:40});assert.equal(state.current().size,40);assert.equal(state.saved.get(referenceBrushes[0].id).size,16);state.select(referenceBrushes[1].id,'per-brush');state.select(referenceBrushes[0].id,'per-brush');assert.equal(state.current().size,40);state.select(referenceBrushes[0].id,'restore');assert.equal(state.current().size,16);const cursor=cursorState(referenceBrushes[0],point(0,0,1));assert.equal(cursor.shape,'round');assert.equal(cursor.barrelRoll,.5);assert.ok(cursor.size>0);});
test('post correction is explicit, bounded and preserves endpoints; unsupported simulations fail clearly',()=>{const samples=[point(0,0),{...point(10,5),y:50},point(20,10)],corrected=correctGeometry(samples,1);assert.deepEqual(corrected[0],samples[0]);assert.deepEqual(corrected.at(-1),samples.at(-1));assert.ok(Math.hypot(corrected[1].x-samples[1].x,corrected[1].y-samples[1].y)<=1);assert.throws(()=>compilePreset(createPreset('wet','wet',{kind:'watercolor',renderer:'wet-1'})),/extension required/);assert.throws(()=>compilePreset(createPreset('post','post',{stabilization:{post:1}})),/explicit/);});
test('corrupted new record cannot replace saved material, geometry or random sequence',()=>{const r=stroke(referenceBrushes[4],[point(20,0),point(30,10)]);r.commands[0][5]=.99;assert.throws(()=>validateRecord(r),/replay mismatch/);});

test('barrel/azimuth wrap uses the shortest angular arc, release metadata never adds paint geometry',()=>{const mid=interpolateAngle(6.2,.1,.5);assert.ok(Math.abs(mid-Math.PI*2)<.1);const b=new CanonicalBuilder(referenceBrushes[0]);b.accept(point(20,0));const before=b.commands.map(c=>Array.from(c));b.release({...point(300,5,0),origin:'release'});b.finish();const r=b.record();assert.equal(r.commands.length,before.length);assert.deepEqual(r.commands.map(c=>[c[0],c[1],c[20],c[21]]),before.map(c=>[c[0],c[1],c[20],c[21]]));assert.equal(r.releaseInput.x,300);assert.equal(r.raw.length,1);assert.deepEqual(validateRecord(r),r);});

test('marker cap applies opacity once; build-up and flow limits select the material path',()=>{const marker=stroke(referenceBrushes[3],[point(30,0),point(40,5)]);const image=cpuReference(marker,80,60);assert.equal(image[(30*80+35)*4+3],Math.round(.45*255));assert.equal(marker.preset.__foundation.opacity,1);const paint=createPreset('build','build',{paint:'build-up',opacity:.2});assert.equal(continuous(compilePreset(paint)),false);const limited=createPreset('limited','limited',{limits:{flow:[0,.5]}});assert.equal(continuous(compilePreset(limited)),false);});

test('cursor matches pressure fallback, mapped color and build-up opacity without double multiplication',()=>{const p=createPreset('cursor','cursor',{renderer:'stamp',paint:'build-up',opacity:.4,color:[1,0,0],pressure:{fallback:.25,smoothing:0},dynamics:[{source:'pressure',target:'size',mode:'multiply',min:0,max:1,curve:[[0,0],[1,1]]},{source:'pressure',target:'hue',mode:'replace',min:1/3,max:1/3,curve:[[0,0],[1,1]]}]});const s={x:30,y:30,t:0,pointerType:'mouse'},cursor=cursorState(p,s),r=stroke(p,[s]);assert.equal(cursor.size,r.commands[0][2]);assert.deepEqual(cursor.color,r.commands[0].slice(8,11));assert.equal(cursor.opacity,.4);assert.equal(cursor.color[1],1);});

test('predicted release metadata is rejected just like predicted paint input',()=>{const b=new CanonicalBuilder(referenceBrushes[0]);b.accept(point(20,0));assert.throws(()=>b.release({...point(20,5,0),origin:'predicted'}),/prediction/);assert.throws(()=>b.release({...point(20,5,0),predicted:true}),/predict/);});

test('swept pencil and soft erase always publish the latest contact, independent of spacing',()=>{for(const source of [referenceBrushes[4],referenceBrushes[6]]){const p=structuredClone(source);p.size=1024;const b=new CanonicalBuilder(p);for(let i=0;i<480;i++)b.accept(point(100+i*.1,i*1000/240));assert.ok(b.commands.length>0&&b.commands.length<=480);assert.equal(b.commands.at(-1)[20],b.geometry.at(-1).t);assert.equal(b.commands.at(-1)[0],b.geometry.at(-1).x);const before=b.commands.map(c=>Array.from(c));b.finish();assert.deepEqual(b.record().commands,before);}});

for(const source of [referenceBrushes[0],referenceBrushes[3],referenceBrushes[5],referenceBrushes[4],referenceBrushes[6]])test('pending '+source.id+' input is displayed on completion with one submission and intact formal geometry',async()=>{
 const p=compilePreset(source),document=new TileDocument(256,256),builder=new CanonicalBuilder(source);
 for(let i=0;i<8;i++)builder.accept({...point(20+i*10,i*5),y:30+(i%2)*10});builder.finish();assert.ok(builder.commands.length>=3);
 document.append(1,p,builder.commands);const retained=document.count,seen=[],pending=[];let inFlight=0,maxInFlight=0;
 const backend={immediatePreview:true,render(snapshot,jobs){inFlight++;maxInFlight=Math.max(maxInFlight,inFlight);seen.push({end:snapshot.stableEnd,jobs:jobs.length});return new Promise(resolve=>pending.push(()=>{inFlight--;resolve();}));},destroy(){}};
 const renderer=new GpuRenderer(backend,256,256),prefixSource=builder.commands;renderer.document=document;
 const send=end=>renderer.setLive({id:1,preset:p,stableSource:prefixSource,stableEnd:end,commands:[],tip:{x:30,y:30,t:performance.now()},finished:false});
 send(1);renderer.frame(performance.now());send(2);send(3);assert.equal(seen.length,1);
 pending.shift()();await new Promise(resolve=>setImmediate(resolve));
 assert.deepEqual(seen,[{end:1,jobs:0},{end:3,jobs:0}]);assert.equal(maxInFlight,1);assert.equal(document.count,retained);
 pending.shift()();await new Promise(resolve=>setImmediate(resolve));assert.equal(seen.length,2);
 send(4);send(5);assert.equal(seen.length,2);await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(seen.at(-1),{end:5,jobs:0});assert.equal(maxInFlight,1);assert.equal(document.count,retained);
 pending.shift()();await new Promise(resolve=>setImmediate(resolve));assert.ok(document.jobs.length>0);renderer.destroy();
});

// A notification without changed artwork can make RAF submit an old tip just
// before the actual input batch, needlessly occupying the only GPU slot.
test('WebGPU Foundation without prediction publishes changed input, not identical RAF notifications',()=>{
 const PreviousWorker=globalThis.Worker;globalThis.Worker=class{postMessage(){}terminate(){}};
 try{for(const source of referenceBrushes){
  const snapshots=[],backend={backend:{immediatePreview:true},setLive:s=>snapshots.push(s),frame:()=>false,destroy(){}};const session=new RealtimeSession(backend);
  session.begin(source);session.accept({...point(20,0),y:30});
  for(let i=1;i<20;i++)session.frame(i);assert.equal(snapshots.length,1,source.id);
  session.accept({...point(21,20),y:31});session.frame(21);assert.equal(snapshots.length,2,source.id);assert.equal(session.active.raw.length,2);
  session.destroy();
 }}finally{globalThis.Worker=PreviousWorker;}
});

test("committed artwork gets a viewport pass without pending live feedback",()=>{
 assert.deepEqual(previewBatches({archivedThrough:-1},[]),[{states:[],archive:false}]);
 assert.deepEqual(previewBatches({archivedThrough:2},[{id:1,finished:true},{id:2,finished:true}]),[{states:[],archive:false}]);
});

test('WebGL2 Foundation keeps the accepted RAF publication cadence',()=>{
 const PreviousWorker=globalThis.Worker;globalThis.Worker=class{postMessage(){}terminate(){}};
 try{const snapshots=[],renderer={backend:{immediatePreview:false},setLive:s=>snapshots.push(s),frame:()=>false,destroy(){}};
 const session=new RealtimeSession(renderer);session.begin(referenceBrushes[4]);session.accept(point(20,0));session.frame(1);session.frame(2);
 assert.equal(snapshots.length,3);assert.equal(session.active.raw.length,1);session.destroy();
 }finally{globalThis.Worker=PreviousWorker;}
});
