import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {CanonicalBuilder,Stabilizer,predict,LatestMailbox,validateRecord,cpuReference,continuous,keysFor,VERSION,liveAccumulation,referenceCoverage} from '../../../prototypes/brush-rt/dist/rt/model.mjs';
import {TileDocument,GpuRenderer,previewDirty,previewBatches} from '../../../prototypes/brush-rt/dist/rt/renderer.mjs';
import {RealtimeSession} from '../../../prototypes/brush-rt/dist/rt/session.mjs';
const presets=JSON.parse(fs.readFileSync(new URL('../../../docs/brush/evidence/presets.json',import.meta.url)));
const ink={...presets.find(p=>p.id==='fine-ink'),size:16,stabilization:1,pressureSmoothing:0};
const point=(i,hz=240)=>({x:10+i/4,y:24+Math.sin(i/30)*4,t:i*1000/hz,pressure:.7,pointerType:'pen',tilt:.3,azimuth:.4,twist:.5});
test('all 56 unchanged presets generate and independently replay version 2 records',()=>{assert.equal(presets.length,56);for(const p of presets){const b=new CanonicalBuilder(p);for(let i=0;i<150;i++)b.accept(point(i));b.finish();const r=b.record();assert.deepEqual(validateRecord(JSON.parse(JSON.stringify(r))),r);assert.deepEqual(r.preset,p);assert.equal(r.raw.length,150);}});
test('prediction never enters records',()=>{const b=new CanonicalBuilder(ink);assert.throws(()=>b.accept({...point(0),predicted:true}),/prediction/);b.accept(point(0));b.finish();assert.ok(!JSON.stringify(b.record()).includes('predicted'));});
test('out-of-order input and non-finite sensors rejected',()=>{const b=new CanonicalBuilder(ink);b.accept(point(2));assert.throws(()=>b.accept(point(1)),/order/);assert.throws(()=>new CanonicalBuilder(ink).accept({...point(1),x:NaN}),/invalid/);});
test('sensors and absent-pressure fallbacks retained',()=>{const b=new CanonicalBuilder(ink);b.accept(point(0));b.accept({x:2,y:2,t:2,pointerType:'mouse',pressure:0});b.finish();assert.equal(b.record().geometry[0].tilt,.3);assert.equal(b.record().geometry[0].azimuth,.4);assert.equal(b.record().geometry[1].p,1);});
test('smoother has no constant-speed phase lag at every tested frequency',()=>{for(const hz of [60,120,240,480]){const s=new Stabilizer(ink);for(let i=0;i<hz*5;i++){const q={x:i*1000/hz,y:20,t:i*1000/hz,pressure:.5,pointerType:'pen'},a=s.accept(q);assert.ok(Math.abs(a.x-q.x)<1e-6);assert.ok(Math.abs(a.y-20)<1e-6);}}});
test('local regression reduces alternating jitter with bounded displacement',()=>{const s=new Stabilizer(ink);let raw=0,filtered=0;for(let i=0;i<500;i++){const q={x:i,y:20+(i%2?2:-2),t:i*1000/240,pressure:1,pointerType:'pen'},a=s.accept(q);if(i>10){raw+=(q.y-20)**2;filtered+=(a.y-20)**2;}assert.ok(Math.hypot(a.x-q.x,a.y-q.y)<=6.00001);}assert.ok(filtered<raw*.8);});
test('corners reset and guarded prediction does not overshoot reversal',()=>{const s=new Stabilizer(ink);for(const q of [{x:0,y:0,t:0},{x:10,y:0,t:10},{x:20,y:0,t:20}])s.accept(q);assert.equal(s.accept({x:10,y:0,t:30}).x,10);assert.equal(predict([{x:0,y:0,t:0},{x:10,y:0,t:10},{x:0,y:0,t:20}],22),null);});
test('prediction time/distance limited and expires after actual input stops',()=>{const p=[{x:0,y:0,t:0},{x:10,y:0,t:10},{x:20,y:0,t:20}];assert.ok(predict(p,22).x<=32);assert.equal(predict(p,100),null);assert.equal(predict(p,22,[{x:200,y:0,t:21}]).x,32);});
test('latest mailbox keeps only newest state, never drops canonical input',()=>{const m=new LatestMailbox,b=new CanonicalBuilder(ink);for(let i=0;i<1000;i++){b.accept(point(i));m.set({i});}assert.equal(m.take().i,999);assert.equal(m.obsolete,999);b.finish();assert.equal(b.record().raw.length,1000);});
test('tampered commands are rejected by independent replay',()=>{const b=new CanonicalBuilder(ink);b.accept(point(0));b.finish();const r=b.record();r.commands[0][0]+=1;assert.throws(()=>validateRecord(r),/mismatch/);});
test('stroke opacity caps overlap and erase preserves color correctly',()=>{const p={...ink,size:16,opacity:.4};const b=new CanonicalBuilder(p);b.accept({x:16,y:16,t:0,pointerType:'mouse'});b.accept({x:16,y:16,t:1,pointerType:'mouse'});b.finish();const a=cpuReference(b.record(),32,32);assert.equal(a[(16*32+16)*4+3],102);const e=new CanonicalBuilder({...p,blend:'erase',opacity:.5});e.accept({x:16,y:16,t:0,pointerType:'mouse'});e.finish();assert.equal(cpuReference(e.record(),32,32,a)[(16*32+16)*4+3],51);});
test('dirty work is clipped to document tiles',()=>{const c=new Array(24).fill(0);c[0]=c[16]=-1e6;c[1]=c[17]=-1e6;c[2]=1024;c[18]=512;assert.deepEqual(keysFor(c,4096,3072),[]);c[0]=c[16]=128;c[1]=c[17]=128;c[2]=16;c[18]=8;assert.equal(keysFor(c,4096,3072).length,4);});
test('confirmed tile batches bounded to 16 commands and preserve order',()=>{const d=new TileDocument(128,128),commands=Array.from({length:100},(_,i)=>{const a=new Array(24).fill(0);a[0]=a[16]=30;a[1]=a[17]=30;a[2]=16;a[18]=8;a[20]=i;return a;});d.append(1,ink,commands);d.end(1,ink);let seen=[];while(d.jobs.length){const j=d.peek();assert.ok(j.commands.length<=16);seen.push(...j.commands.map(c=>c[20]));d.complete(j);}assert.deepEqual(seen,commands.map(c=>c[20]));});
test('formal stall cannot create a FIFO of submitted live snapshots',async()=>{let release=null,submitted=[];const fake={info:{backend:'simulation'},render(s,j){submitted.push(s?.tip.t);return new Promise(r=>release=r);},poll(){},destroy(){}};const g=new GpuRenderer(fake,128,128);g.setLive({tip:{x:0,y:0,t:0},commands:[]});g.frame(0);for(let i=1;i<1000;i++){g.setLive({tip:{x:i,y:0,t:i},commands:[]});g.frame(i);}assert.deepEqual(submitted,[0]);release();await Promise.resolve();g.frame(1000);assert.deepEqual(submitted,[0,999]);release();await Promise.resolve();});
test('size/frequency/180-second scheduling simulation retains every input without live backlog',()=>{for(const size of [16,128,512,1024])for(const hz of [60,120,240,480]){const b=new CanonicalBuilder({...ink,size}),m=new LatestMailbox;let first=[],last=[];for(let i=0;i<hz*180;i++){b.accept({x:64+Math.sin(i/hz)*30,y:64+Math.cos(i/hz)*30,t:i*1000/hz,pressure:1,pointerType:'pen'});m.set({t:i*1000/hz});if(i%Math.max(1,hz/60)===0){const now=i*1000/hz,age=now-m.take().t;if(i<hz)first.push(age);if(i>=hz*179)last.push(age);}}b.finish();assert.equal(b.record().raw.length,hz*180);assert.equal(Math.max(...first),0);assert.equal(Math.max(...last),0);}});

test('frame integration keeps worker and latest display independent',()=>{const original=globalThis.Worker,messages=[],snapshots=[];globalThis.Worker=class{postMessage(m){messages.push(m);}terminate(){}};try{const r={setLive:x=>snapshots.push(x),frame:()=>true},session=new RealtimeSession(r,'mock');session.begin(ink);session.accept(point(0));session.accept(point(1));assert.equal(session.frame(20),true);assert.equal(messages.at(-1).samples.length,2);assert.equal(snapshots.at(-1).rawTip.t,point(1).t);}finally{globalThis.Worker=original;}});
test('in-flight confirmed chunks stay frozen across worker arrivals',()=>{const d=new TileDocument(128,128),command=t=>{const a=new Array(24).fill(0);a[0]=a[16]=30;a[1]=a[17]=30;a[2]=16;a[18]=8;a[20]=t;return a;};d.append(1,ink,Array.from({length:20},(_,i)=>command(i)));const batch=d.peekMany(2);d.append(1,ink,[command(20)]);for(const j of batch)d.complete(j);assert.deepEqual(d.peek().commands.map(c=>c[20]),[20]);});
test('airbrush time deposits replay from two real stationary timestamps',()=>{for(const p of presets.filter(p=>p.exposureMs)){const b=new CanonicalBuilder({...p,stabilization:0});b.accept({x:32,y:32,t:0,pressure:1,pointerType:'pen'});b.accept({x:32,y:32,t:1000,pressure:1,pointerType:'pen'});b.finish();const r=b.record();assert.equal(r.raw.length,2);assert.ok(r.commands.length>=Math.floor(1000/p.exposureMs));assert.deepEqual(validateRecord(r),r);for(let i=1;i<r.commands.length;i++)assert.ok(r.commands[i][20]>=r.commands[i-1][20]);}});

test('continuous solid AA union is independent of input sampling density',()=>{let reference=null;for(const hz of [60,120,240]){const b=new CanonicalBuilder({...ink,size:16,opacity:.4,stabilization:0,mappings:[]});for(let i=0;i<=hz;i++)b.accept({x:12+72*i/hz,y:24,t:i*1000/hz,pressure:1,pointerType:'pen'});b.finish();const pixels=cpuReference(b.record(),96,48);if(reference)for(let i=0;i<pixels.length;i++)assert.ok(Math.abs(pixels[i]-reference[i])<=1);else reference=pixels;}});

test('only provably saturated constant-pigment tiles elide further GPU work',()=>{const p={...ink,size:1024,stabilization:0},b=new CanonicalBuilder(p);for(let i=0;i<100;i++)b.accept({x:64+Math.sin(i)*2,y:64,t:i,pressure:1,pointerType:'pen'});b.finish();const d=new TileDocument(128,128);d.append(1,p,b.record().commands);const first=d.peekMany(1);d.complete(first[0]);const next=d.peekMany(1);assert.equal(next[0].skip,true);assert.ok(next[0].commands.length>16);const soft={...p,flow:.5};const x=new TileDocument(128,128);x.append(1,soft,b.record().commands);x.complete(x.peekMany(1)[0]);assert.notEqual(x.peekMany(1)[0].skip,true);});

test('already saturated solid tiles do not grow the formal queue on later actual input',()=>{const p={...ink,size:1024,stabilization:0},b=new CanonicalBuilder(p);b.accept({x:64,y:64,t:0,pointerType:'mouse'});b.finish();const d=new TileDocument(128,128);d.append(1,p,b.record().commands);d.complete(d.peekMany(1)[0]);for(let i=1;i<1000;i++)d.append(1,p,b.record().commands.map(c=>{const a=c.slice();a[20]=i;return a;}));assert.equal(d.jobs.length,0);assert.equal(d.count,0);assert.equal(d.knownTime,999);d.end(1,p);assert.equal(d.peek().commit,true);});

test('complex density mode keeps varying flow but rejects varying pigment or stroke opacity',()=>{assert.ok(liveAccumulation(presets[0]));assert.ok(liveAccumulation(presets[13]));assert.ok(!liveAccumulation(presets[11]));assert.ok(!liveAccumulation(presets[44]));assert.ok(!liveAccumulation(ink));});

test('hard ellipse AA stays continuous across Float32 command rounding',()=>{const p=presets[50],c=new Array(24).fill(0);c[0]=32.000001;c[1]=32;c[2]=20;c[3]=.45;c[4]=.41;for(let y=24;y<42;y++)for(let x=20;x<45;x++){const a=referenceCoverage(c,x+.5,y+.5,p),b=referenceCoverage(c.map(Math.fround),x+.5,y+.5,p);assert.ok(Math.abs(a-b)<.0001);}});
test('quantized zero alpha never retains hidden reference pigment',()=>{const b=new CanonicalBuilder({...ink,size:16,opacity:.0001,color:[.7,.2,.1]});b.accept({x:16,y:16,t:0,pointerType:'mouse'});b.finish();const pixels=cpuReference(b.record(),32,32);assert.ok(pixels.every(v=>v===0));});

test('completed cached feedback is archived before a fifth pending stroke, without halting latest input',()=>{const backend={previews:new Map([1,2,3,4].map(id=>[id,{}])),archivedThrough:-1,obsoleteFinished:0},states=[1,2,3,4,5].map(id=>({id,finished:id<5})),b=previewBatches(backend,states);assert.equal(b[0].archive,true);assert.deepEqual(b[0].states.map(s=>s.id),[1,2,3,4]);assert.deepEqual(b[1].states.map(s=>s.id),[5]);assert.equal(backend.obsoleteFinished,0);});
test('never displayed obsolete snapshots have bounded work while the newest stroke is selected',()=>{const backend={previews:new Map,archivedThrough:-1,obsoleteFinished:0},states=Array.from({length:20},(_,i)=>({id:i+1,finished:i<19})),b=previewBatches(backend,states);assert.deepEqual(b[0].states.map(s=>s.id),[17,18,19,20]);assert.equal(backend.obsoleteFinished,16);assert.equal(backend.archivedThrough,16);assert.equal(states.length,20);});
test('predicted-only tiles cannot become feedback archive coverage and are dirtied on prediction removal',()=>{const c=t=>{const a=new Array(24).fill(0);a[0]=a[16]=t>10?400:20;a[1]=a[17]=20;a[2]=16;a[18]=8;a[19]=1;a[20]=t;return a;},v={preset:ink,keys:new Set},dirty=new Set;previewDirty(v,[c(10)],[c(12)],512,384,dirty,10);assert.ok(v.keys.has('3,0'));assert.ok(!v.realKeys.has('3,0'));dirty.clear();previewDirty(v,[],[],512,384,dirty,10);assert.ok(dirty.has('3,0'));});
