import {summarize} from '../../../prototypes/brush-rt/dist/rt/ui.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {CanonicalBuilder,Stabilizer,predict,LatestMailbox,validateRecord,cpuReference,continuous,keysFor,VERSION,liveAccumulation,referenceCoverage} from '../../../prototypes/brush-rt/dist/rt/model.mjs';
import {TileDocument,GpuRenderer,previewDirty,previewBatches,livePrefixCommands,publishedCommands} from '../../../prototypes/brush-rt/dist/rt/renderer.mjs';
import {RealtimeSession,predictedCommand} from '../../../prototypes/brush-rt/dist/rt/session.mjs';
const presets=JSON.parse(fs.readFileSync(new URL('../../../docs/brush/evidence/presets.json',import.meta.url)));
const ink={...presets.find(p=>p.id==='fine-ink'),size:16,stabilization:1,pressureSmoothing:0};
const point=(i,hz=240)=>({x:10+i/4,y:24+Math.sin(i/30)*4,t:i*1000/hz,pressure:.7,pointerType:'pen',tilt:.3,azimuth:.4,twist:.5});
test('all 56 unchanged presets generate and independently replay version 2 records',()=>{assert.equal(presets.length,56);for(const p of presets){const b=new CanonicalBuilder(p);for(let i=0;i<150;i++)b.accept(point(i));b.finish();const r=b.record();assert.deepEqual(validateRecord(JSON.parse(JSON.stringify(r))),r);assert.deepEqual(r.preset,p);assert.equal(r.raw.length,150);}});
test('prediction never enters records',()=>{const b=new CanonicalBuilder(ink);assert.throws(()=>b.accept({...point(0),predicted:true}),/prediction/);b.accept(point(0));b.finish();assert.ok(!JSON.stringify(b.record()).includes('predicted'));});
test('out-of-order input and non-finite sensors rejected',()=>{const b=new CanonicalBuilder(ink);b.accept(point(2));assert.throws(()=>b.accept(point(1)),/order/);assert.throws(()=>new CanonicalBuilder(ink).accept({...point(1),x:NaN}),/invalid/);});
test('sensors and absent-pressure fallbacks retained',()=>{const b=new CanonicalBuilder(ink);b.accept(point(0));b.accept({x:2,y:2,t:2,pointerType:'mouse',pressure:0});b.finish();assert.equal(b.record().geometry[0].tilt,.3);assert.equal(b.record().geometry[0].azimuth,.4);assert.equal(b.record().geometry[1].p,1);});
test('smoother has no constant-speed phase lag at every tested frequency',()=>{for(const hz of [60,120,240,480]){const s=new Stabilizer(ink);for(let i=0;i<hz*5;i++){const q={x:i*1000/hz,y:20,t:i*1000/hz,pressure:.5,pointerType:'pen'},a=s.accept(q);assert.ok(Math.abs(a.x-q.x)<1e-6);assert.ok(Math.abs(a.y-20)<1e-6);}}});
test('local regression reduces alternating jitter with bounded displacement',()=>{const s=new Stabilizer(ink);let raw=0,filtered=0;for(let i=0;i<500;i++){const q={x:i,y:20+(i%2?2:-2),t:i*1000/240,pressure:1,pointerType:'pen'},a=s.accept(q);if(i>10){raw+=(q.y-20)**2;filtered+=(a.y-20)**2;}assert.ok(Math.hypot(a.x-q.x,a.y-q.y)<=6.00001);}assert.ok(filtered<raw*.8);});
test('corners reset and guarded prediction does not overshoot reversal',()=>{const s=new Stabilizer(ink);for(const q of [{x:0,y:0,t:0},{x:10,y:0,t:10},{x:20,y:0,t:20}])s.accept(q);assert.equal(s.accept({x:10,y:0,t:30}).x,10);assert.equal(predict([{x:0,y:0,t:0},{x:10,y:0,t:10},{x:0,y:0,t:20}],22),null);});
test('prediction time/distance limited and expires after actual input stops',()=>{const p=[{x:0,y:0,t:0},{x:10,y:0,t:10},{x:20,y:0,t:20}];assert.ok(predict(p,22).x<=32);assert.equal(predict(p,100),null);assert.equal(predict(p,22,[{x:200,y:0,t:21}]).x,32);});
test('latest mailbox keeps only newest state, never drops canonical input',()=>{const m=new LatestMailbox,b=new CanonicalBuilder(ink);for(let i=0;i<1000;i++){b.accept(point(i));m.set({i});}assert.equal(m.take().i,999);assert.equal(m.obsolete,999);b.finish();assert.equal(b.record().raw.length,1000);});
test('tampered commands are rejected by independent replay',()=>{const b=new CanonicalBuilder(ink);b.accept(point(0));b.finish();const r=b.record();r.commands[0][0]+=1;assert.throws(()=>validateRecord(r),/mismatch/);});
test('stroke opacity caps overlap and erase preserves color correctly',()=>{const p={...ink,size:16,opacity:.4};const b=new CanonicalBuilder(p);b.accept({x:16,y:16,t:0,pointerType:'mouse'});b.accept({x:16,y:16,t:1,pointerType:'mouse'});b.finish();const a=cpuReference(b.record(),32,32);assert.equal(a[(16*32+16)*4+3],102);const e=new CanonicalBuilder({...p,blend:'erase',opacity:.5});e.accept({x:16,y:16,t:0,pointerType:'mouse'});e.finish();assert.equal(cpuReference(e.record(),32,32,a)[(16*32+16)*4+3],51);});
test('dirty work is clipped to document tiles',()=>{const c=new Array(24).fill(0);c[0]=c[16]=-1e6;c[1]=c[17]=-1e6;c[2]=1024;c[18]=512;assert.deepEqual(keysFor(c,4096,3072),[]);c[0]=c[16]=128;c[1]=c[17]=128;c[2]=16;c[18]=8;assert.equal(keysFor(c,4096,3072).length,4);});
test('confirmed tile batches bounded to 16 commands and preserve order',()=>{const d=new TileDocument(128,128),commands=Array.from({length:100},(_,i)=>{const a=new Array(24).fill(0);a[0]=a[16]=30;a[1]=a[17]=30;a[2]=16;a[18]=8;a[20]=i;return a;});d.append(1,ink,commands);d.end(1,ink);let seen=[];while(d.jobs.length){const j=d.peek();assert.ok(j.commands.length<=16);seen.push(...j.commands.map(c=>c[20]));d.complete(j);}assert.deepEqual(seen,commands.map(c=>c[20]));});
test('formal stall cannot create a FIFO of submitted live snapshots',async()=>{let release=null,submitted=[];const fake={info:{backend:'simulation'},render(s,j){submitted.push(s?.tip.t);return new Promise(r=>release=r);},poll(){},destroy(){}};const g=new GpuRenderer(fake,128,128);g.setLive({tip:{x:0,y:0,t:0},commands:[]});g.frame(0);for(let i=1;i<1000;i++){g.setLive({tip:{x:i,y:0,t:i},commands:[]});g.frame(i);}assert.deepEqual(submitted,[0]);release();await Promise.resolve();g.frame(1000);assert.deepEqual(submitted,[0,999]);release();await Promise.resolve();});
test('size/frequency/180-second scheduling simulation retains every input without live backlog',()=>{for(const size of [16,128,512,1024])for(const hz of [60,120,240,480]){const b=new CanonicalBuilder({...ink,size}),m=new LatestMailbox;let first=[],last=[];for(let i=0;i<hz*180;i++){b.accept({x:64+Math.sin(i/hz)*30,y:64+Math.cos(i/hz)*30,t:i*1000/hz,pressure:1,pointerType:'pen'});m.set({t:i*1000/hz});if(i%Math.max(1,hz/60)===0){const now=i*1000/hz,age=now-m.take().t;if(i<hz)first.push(age);if(i>=hz*179)last.push(age);}}b.finish();assert.equal(b.record().raw.length,hz*180);assert.equal(Math.max(...first),0);assert.equal(Math.max(...last),0);}});

test('frame integration keeps worker and latest display independent',()=>{const original=globalThis.Worker,messages=[],snapshots=[];globalThis.Worker=class{postMessage(m){messages.push(m);}terminate(){}};try{const r={setLive:x=>snapshots.push(x),frame:()=>true},session=new RealtimeSession(r,'mock');session.begin(ink);session.accept(point(0));session.accept(point(1));assert.equal(session.frame(20),true);assert.equal(messages.at(-1).samples.length,2);assert.equal(snapshots.at(-1).rawTip.t,point(1).t);}finally{globalThis.Worker=original;}});
test('in-flight confirmed chunks stay frozen across worker arrivals',()=>{const d=new TileDocument(128,128),command=t=>{const a=new Array(24).fill(0);a[0]=a[16]=30;a[1]=a[17]=30;a[2]=16;a[18]=8;a[20]=t;return a;};d.append(1,ink,Array.from({length:20},(_,i)=>command(i)));const batch=d.peekMany(2);d.append(1,ink,[command(20)]);for(const j of batch)d.complete(j);assert.deepEqual(d.peek().commands.map(c=>c[20]),[20]);});
test('airbrush time deposits replay from two real stationary timestamps',()=>{for(const p of presets.filter(p=>p.exposureMs)){const b=new CanonicalBuilder({...p,stabilization:0});b.accept({x:32,y:32,t:0,pressure:1,pointerType:'pen'});b.accept({x:32,y:32,t:1000,pressure:1,pointerType:'pen'});b.finish();const r=b.record();assert.equal(r.raw.length,2);assert.ok(r.commands.length>=Math.floor(1000/p.exposureMs));assert.deepEqual(validateRecord(r),r);for(let i=1;i<r.commands.length;i++)assert.ok(r.commands[i][20]>=r.commands[i-1][20]);}});

test('continuous solid AA union is independent of input sampling density',()=>{let reference=null;for(const hz of [60,120,240]){const b=new CanonicalBuilder({...ink,size:16,opacity:.4,stabilization:0,mappings:[]});for(let i=0;i<=hz;i++)b.accept({x:12+72*i/hz,y:24,t:i*1000/hz,pressure:1,pointerType:'pen'});b.finish();const pixels=cpuReference(b.record(),96,48);if(reference)for(let i=0;i<pixels.length;i++)assert.ok(Math.abs(pixels[i]-reference[i])<=1);else reference=pixels;}});

test('only provably saturated constant-pigment tiles elide further GPU work',()=>{const p={...ink,size:1024,stabilization:0},b=new CanonicalBuilder(p);for(let i=0;i<100;i++)b.accept({x:64+Math.sin(i)*2,y:64,t:i,pressure:1,pointerType:'pen'});b.finish();const d=new TileDocument(128,128);d.append(1,p,b.record().commands);const first=d.peekMany(1);d.complete(first[0]);const next=d.peekMany(1);assert.equal(next[0].skip,true);assert.ok(next[0].commands.length>16);const soft={...p,flow:.5};const x=new TileDocument(128,128);x.append(1,soft,b.record().commands);x.complete(x.peekMany(1)[0]);assert.notEqual(x.peekMany(1)[0].skip,true);});

test('already saturated solid tiles do not grow the formal queue on later actual input',()=>{const p={...ink,size:1024,stabilization:0},b=new CanonicalBuilder(p);b.accept({x:64,y:64,t:0,pointerType:'mouse'});b.finish();const d=new TileDocument(128,128);d.append(1,p,b.record().commands);d.complete(d.peekMany(1)[0]);for(let i=1;i<1000;i++)d.append(1,p,b.record().commands.map(c=>{const a=c.slice();a[20]=i;return a;}));assert.equal(d.jobs.length,0);assert.equal(d.count,0);assert.equal(d.knownTime,999);d.end(1,p);assert.equal(d.peek().commit,true);});

test('complex density mode keeps varying flow but rejects varying pigment or stroke opacity',()=>{assert.ok(liveAccumulation(presets[0]));assert.ok(liveAccumulation(presets[13]));assert.ok(!liveAccumulation(presets[11]));assert.ok(!liveAccumulation(presets[44]));assert.ok(!liveAccumulation(ink));});

test('hard ellipse AA stays continuous across Float32 command rounding',()=>{const p=presets[50],c=new Array(24).fill(0);c[0]=32.000001;c[1]=32;c[2]=20;c[3]=.45;c[4]=.41;for(let y=24;y<42;y++)for(let x=20;x<45;x++){const a=referenceCoverage(c,x+.5,y+.5,p),b=referenceCoverage(c.map(Math.fround),x+.5,y+.5,p);assert.ok(Math.abs(a-b)<.0001);}});
test('quantized zero alpha never retains hidden reference pigment',()=>{const b=new CanonicalBuilder({...ink,size:16,opacity:.0001,color:[.7,.2,.1]});b.accept({x:16,y:16,t:0,pointerType:'mouse'});b.finish();const pixels=cpuReference(b.record(),32,32);assert.ok(pixels.every(v=>v===0));});

test('completed cached feedback is archived before a fifth pending stroke, without halting latest input',()=>{const backend={previews:new Map([1,2,3,4].map(id=>[id,{}])),archivedThrough:-1,obsoleteFinished:0},states=[1,2,3,4,5].map(id=>({id,finished:id<5})),b=previewBatches(backend,states);assert.equal(b[0].archive,true);assert.deepEqual(b[0].states.map(s=>s.id),[1,2,3,4]);assert.deepEqual(b[1].states.map(s=>s.id),[5]);assert.equal(backend.obsoleteFinished,0);});
test('never displayed obsolete snapshots have bounded work while the newest stroke is selected',()=>{const backend={previews:new Map,archivedThrough:-1,obsoleteFinished:0},states=Array.from({length:20},(_,i)=>({id:i+1,finished:i<19})),b=previewBatches(backend,states);assert.deepEqual(b[0].states.map(s=>s.id),[17,18,19,20]);assert.equal(backend.obsoleteFinished,16);assert.equal(backend.archivedThrough,16);assert.equal(states.length,20);});
test('predicted-only tiles cannot become feedback archive coverage and are dirtied on prediction removal',()=>{const c=t=>{const a=new Array(24).fill(0);a[0]=a[16]=t>10?400:20;a[1]=a[17]=20;a[2]=16;a[18]=8;a[19]=1;a[20]=t;return a;},v={preset:ink,keys:new Set},dirty=new Set;previewDirty(v,[c(10)],[c(12)],512,384,dirty,10);assert.ok(v.keys.has('3,0'));assert.ok(!v.realKeys.has('3,0'));dirty.clear();previewDirty(v,[],[],512,384,dirty,10);assert.ok(dirty.has('3,0'));});

test('strong constant correction reduces jitter at 60,120,240 and480Hz without waiting for future input',()=>{for(const hz of [60,120,240,480]){const f=new Stabilizer(ink);let raw=0,filtered=0;for(let i=0;i<500;i++){const s={x:i,y:20+(i%2?2:-2),t:i*1000/hz,pressure:1,pointerType:'pen'},q=f.accept(s);assert.equal(q.t,s.t);assert.ok(Math.hypot(q.x-s.x,q.y-s.y)<=6.00001);if(i>10){raw+=(s.y-20)**2;filtered+=(q.y-20)**2;}}assert.ok(filtered<raw*.8,'jitter at '+hz+'Hz');}});

test('identical GPU solid shape tuples are elided without changing retained raw data or known input time',()=>{const p={...ink,stabilization:0},b=new CanonicalBuilder(p);for(let i=0;i<1000;i++)b.accept({x:32,y:32,t:i,pointerType:'mouse'});b.finish();const r=b.record(),d=new TileDocument(128,128);d.append(1,p,r.commands);assert.equal(d.count,1);assert.equal(d.knownTime,999);assert.equal(r.raw.length,1000);assert.equal(r.commands.length,1000);const complex=new TileDocument(128,128);complex.append(1,{...p,flow:.5},r.commands);assert.equal(complex.count,1000);});
test('incremental live bands require an existing same-radius predecessor and never alter canonical commands',()=>{const p={...ink,size:512,stabilization:0},b=new CanonicalBuilder(p);for(let i=0;i<4;i++)b.accept({x:180+i*10,y:200,t:i,pointerType:'mouse'});b.finish();const commands=b.record().commands,v={preset:p,fullTiles:new Set};const q=livePrefixCommands(v,p,commands,1024,768);assert.notEqual(q.stable[0][23],-1);assert.ok(q.stable.slice(1).every(c=>c[23]===-1));assert.equal(q.vertexCount,q.sectors*12);assert.ok(q.vertexCount<=384);assert.ok(commands.every(c=>c[23]>=0));const gap=commands.at(-1).slice();gap[16]=800;assert.notEqual(livePrefixCommands(v,p,[gap],1024,768).stable[0][23],-1);});


test('spaced round presets keep visible gaps instead of becoming capsules',()=>{for(const index of [45,46]){const p={...presets[index],size:10,stabilization:0,mappings:[]};assert.equal(continuous(p),false);const b=new CanonicalBuilder(p);for(let i=0;i<=80;i++)b.accept({x:20+i,y:30,t:i,pointerType:'mouse'});b.finish();const r=b.record(),a=cpuReference(r,128,64);assert.equal(r.raw.length,81);assert.ok(r.commands.every(c=>c[19]===0));assert.ok(a[(30*128+20)*4+3]>0);assert.equal(a[(30*128+27)*4+3],0);}});
test('display prediction respects stamp spacing and never mutates replay state',()=>{const b=new CanonicalBuilder({...presets[45],size:10,stabilization:0,mappings:[]});for(let i=0;i<=4;i++)b.accept({x:20+i,y:30,t:i,pointerType:'mouse'});const before=JSON.stringify({raw:b.raw,commands:b.commands,index:b.index,carry:b.carry});assert.equal(predictedCommand(b,{...b.geometry.at(-1),x:28,t:8}),null);const c=predictedCommand(b,{...b.geometry.at(-1),x:38,t:18});assert.ok(c);assert.equal(c[0],35);assert.equal(c[19],0);assert.equal(JSON.stringify({raw:b.raw,commands:b.commands,index:b.index,carry:b.carry}),before);});
test('stamp tip metrics track the actual deposited stamp rather than the raw cursor',()=>{const original=globalThis.Worker,snapshots=[];globalThis.Worker=class{postMessage(){}terminate(){}};try{const session=new RealtimeSession({setLive:s=>snapshots.push(s)},'mock');session.prediction=false;session.begin({...presets[45],size:10,stabilization:0,mappings:[]});for(let i=0;i<=4;i++)session.accept({x:20+i,y:30,t:i,pointerType:'mouse'});const s=snapshots.at(-1);assert.equal(s.inputTip.x,24);assert.equal(s.previewTip.x,20);assert.equal(s.tip.t,0);assert.equal(s.inputTip.t,4);}finally{globalThis.Worker=original;}});

test('adaptive band sectors conservatively cover the complete capsule AA boundary through4096px',()=>{for(const size of [256,512,1024,4096]){const p={...ink,size,stabilization:0},b=new CanonicalBuilder(p);for(let i=0;i<3;i++)b.accept({x:300+i*10,y:300,t:i,pointerType:'mouse'});b.finish();const q=livePrefixCommands({preset:p,fullTiles:new Set},p,b.record().commands,4096,3072),r=size/2;assert.ok((r+2)*Math.cos(Math.PI/(2*q.sectors))>=r+.5);assert.ok(q.sectors<=64);}});

test('cold first-second cost cannot hide later growth and insufficient windows do not pass',()=>{const values=(age,base)=>[100,300,600].map(t=>({completedAt:base+t,inputAge:age}));const r=summarize([...values(400,0),...values(20,1000),...values(200,3000)],0,4000);assert.ok(r.growth<0);assert.equal(r.steadyGrowth,180);assert.equal(r.growthGate,'FAIL_OR_INSUFFICIENT');assert.equal(summarize([...values(40,0),{completedAt:1200,inputAge:30},...values(30,3000)],0,4000).growthGate,'FAIL_OR_INSUFFICIENT');assert.equal(summarize([...values(40,0),...values(30,1000),...values(32,3000)],0,4000).growthGate,'PASS_PROXY');});

test('undo waits for an ended canonical worker record before choosing the latest stroke',async()=>{const original=globalThis.Worker;globalThis.Worker=class{postMessage(){}terminate(){}};try{let resets=0;const renderer={setLive(){},markEnded(){},document:{end(){},append(){}},async reset(){resets++;},async drain(){}},session=new RealtimeSession(renderer,'mock');session.begin(ink);session.accept(point(0));const ended=session.end(),undone=session.undo();await Promise.resolve();assert.equal(resets,0);const b=new CanonicalBuilder(ink,[0x12345678,1]);b.accept(point(0));b.finish();session.worker.onmessage({data:{type:'record',id:1,record:b.record()}});await Promise.all([ended,undone]);assert.equal(resets,1);assert.equal(session.records.length,0);assert.equal(session.redoRecords.length,1);await session.redo();assert.equal(session.records.length,1);}finally{globalThis.Worker=original;}});

test('same-time tilt azimuth and twist changes remain actual canonical input',()=>{const original=globalThis.Worker;globalThis.Worker=class{postMessage(){}terminate(){}};try{const session=new RealtimeSession({setLive(){}},'mock');session.begin(ink);session.accept(point(0));session.accept({...point(0),tilt:.8,azimuth:.9,twist:1.2});session.accept({...point(0),tilt:.8,azimuth:.9,twist:1.2});assert.equal(session.active.raw.length,2);assert.equal(session.active.builder.geometry.at(-1).tilt,.8);assert.equal(session.active.builder.geometry.at(-1).azimuth,.9);assert.equal(session.active.builder.geometry.at(-1).twist,1.2);}finally{globalThis.Worker=original;}});
test('a stationary pressure increase paints the new radius immediately',()=>{const p={...ink,size:32,stabilization:0,pressureSmoothing:0},b=new CanonicalBuilder(p);b.accept({x:32,y:32,t:0,pressure:.1,pointerType:'pen'});b.accept({x:32,y:32,t:10,pressure:1,pointerType:'pen'});b.finish();const r=b.record(),pixels=cpuReference(r,64,64);assert.equal(r.commands.at(-1)[18],16);assert.ok(pixels[(32*64+44)*4+3]>0);assert.deepEqual(validateRecord(r),r);});
test('v2.4 candidate records preserve their original replay and image rather than silently upgrading',()=>{const b=new CanonicalBuilder({...ink,size:32,stabilization:0,pressureSmoothing:0});b.compatLegacyRadius=true;b.replayEngine='illustro-rt-2.4';b.accept({x:32,y:32,t:0,pressure:.1,pointerType:'pen'});b.accept({x:32,y:32,t:10,pressure:1,pointerType:'pen'});b.finish();const r=b.record(),loaded=validateRecord(JSON.parse(JSON.stringify(r)));assert.deepEqual(loaded,r);assert.equal(loaded.engine,'illustro-rt-2.4');assert.deepEqual(cpuReference(loaded,64,64),cpuReference(r,64,64));});

test('hard star AA remains continuous under Float32 rounding at large coordinates',()=>{const p=presets[55],c=new Array(24).fill(0);c[0]=1680.00004;c[1]=1130.00003;c[2]=128;c[3]=1;c[4]=.31;let max=0;for(let y=1060;y<1200;y++)for(let x=1610;x<1750;x++)max=Math.max(max,Math.abs(referenceCoverage(c,x+.5,y+.5,p)-referenceCoverage(c.map(Math.fround),x+.5,y+.5,p)));assert.ok(max<.002);});


test('superseded thin pencil snapshots retain every unseen dab and freeze their end',()=>{const original=globalThis.Worker,snapshots=[];globalThis.Worker=class{postMessage(){}terminate(){}};try{for(const size of [1,4,16]){const session=new RealtimeSession({setLive:s=>snapshots.push(s)},'mock');session.prediction=false;session.begin({...presets[0],size,stabilization:0,mappings:[],taperStart:0,taperEnd:0});session.accept({x:20,y:30,t:0,pointerType:'mouse'});const first=snapshots.at(-1);for(let i=1;i<=12;i++)session.accept({x:20+i*40,y:30,t:i,pointerType:'mouse'});const last=snapshots.at(-1),v={index:-1};assert.ok(last.stableEnd>64);assert.equal(publishedCommands(first,v).length,first.stableEnd);const unseen=publishedCommands(last,v);assert.equal(unseen.length,last.stableEnd-first.stableEnd);assert.equal(publishedCommands(last,v).length,0);assert.equal(last.stableEnd,session.active.builder.published);assert.deepEqual(last.stableSource.map(c=>c[13]),session.active.builder.commands.slice(0,last.stableEnd).map(c=>c[13]));assert.equal(last.commands.length,session.active.builder.commands.length-last.stableEnd);}}finally{globalThis.Worker=original;}});
