import fs from 'node:fs/promises';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire}from 'node:module';
const require=createRequire(import.meta.url),pw=require(process.env.RT_PLAYWRIGHT_PATH??'playwright'),root=path.resolve(import.meta.dirname,'../..'),evidence=path.join(root,'docs/brush-rt/evidence');await fs.mkdir(evidence,{recursive:true});
const html=await fs.readFile(path.join(import.meta.dirname,'dist/illustro-brush-rt.html'));
const server=http.createServer((q,r)=>{r.setHeader('Content-Type','text/html; charset=utf-8');r.end(html);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;
const browser=await pw.chromium.launch({headless:true,args:['--enable-unsafe-webgpu','--use-angle=swiftshader','--enable-unsafe-swiftshader','--use-vulkan=swiftshader','--enable-features=Vulkan','--disable-vulkan-surface']});
let failed=false;const report={date:new Date().toISOString(),environment:'headless Chromium / software adapter expected; NOT real stylus or photon measurement',backends:[]};
const checkpoint=()=>fs.writeFile(path.join(evidence,'browser-results.json'),JSON.stringify(report,null,2));
try{for(const backend of process.env.RT_BACKEND?[process.env.RT_BACKEND]:['webgl2','webgpu']){const page=await browser.newPage({viewport:{width:1280,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});const r={backend,checks:[],benchmarks:[]};report.backends.push(r);try{await page.goto(`http://127.0.0.1:${port}/?backend=${backend}&document=512`);await page.waitForFunction(()=>window.__rt||document.getElementById('status').classList.contains('danger'),{timeout:30000});const available=await page.evaluate(()=>!!window.__rt);if(!available){r.status='UNAVAILABLE';r.message=await page.locator('#status').textContent();failed=true;await checkpoint();continue;}r.info=await page.evaluate(()=>window.__rt.renderer.info);r.capabilities=await page.evaluate(()=>({raw:'onpointerrawupdate'in window,coalesced:typeof PointerEvent.prototype.getCoalescedEvents==='function',predictedApi:typeof PointerEvent.prototype.getPredictedEvents==='function'}));
 // Mouse input reaches the native pointer path, then save/undo/redo compare pixels.
 const box=await page.locator('#draw').boundingBox();await page.mouse.move(box.x+box.width*.2,box.y+box.height*.4);await page.mouse.down();await page.mouse.move(box.x+box.width*.7,box.y+box.height*.6,{steps:30});await page.mouse.up();await page.waitForFunction(()=>window.__rt.session.records.length===1);
 let v=await page.evaluate(()=>window.__rt.compare());r.checks.push({name:'mouse-reference',...v});assert.ok(v.maxChannelError<=3,JSON.stringify(v));const before=await page.evaluate(()=>JSON.stringify(window.__rt.session.export()));await page.getByRole('button',{name:'取り消す',exact:true}).click();await page.waitForFunction(()=>window.__rt.session.records.length===0&&!document.getElementById('undo').disabled);await page.getByRole('button',{name:'やり直す',exact:true}).click();await page.waitForFunction(()=>window.__rt.session.records.length===1&&!document.getElementById('redo').disabled);assert.equal(await page.evaluate(()=>JSON.stringify(window.__rt.session.export())),before);r.checks.push({name:'undo-redo-canonical',status:'PASS'});
 await page.screenshot({path:path.join(evidence,backend+'-desktop.png'),fullPage:true});
 // All presets, same sensor sequence, CPU f64 final reference. Not previous PASS.
 for(let index=0;index<56;index++){v=await page.evaluate(async index=>{const {session,renderer,presets}=window.__rt;session.records=[];await session.rebuild();session.begin({...presets[index],size:20,stabilization:.25});const inputStart=performance.now();for(let i=0;i<8;i++)session.accept({x:40+i*3,y:60+Math.sin(i)*4,t:inputStart+i*1000/240,pressure:.2+i*.1,pointerType:'pen',tilt:.3,azimuth:.4,twist:.5});await session.end();return window.__rt.compare();},index);r.checks.push({name:'preset-'+index,...v});await checkpoint();console.log('RT_PIXEL:'+JSON.stringify({backend,index,...v}));if(v.channelsOver3&&!v.visualChannelsOver3)r.rawNumericalDifferences=(r.rawNumericalDifferences??[]).concat({index,...v});if(v.visualChannelsOver3)r.pixelDifferences=(r.pixelDifferences??[]).concat({index,...v});}
 // Blend sequence includes pressure, opacity and erase on a colored transparent layer.
 for(const blend of ['normal','multiply','screen','erase']){v=await page.evaluate(async blend=>{const {session,presets}=window.__rt;const p={...presets.find(p=>p.id==='fine-ink'),blend,size:24,opacity:.6,color:[.7,.2,.1]};session.begin(p);for(let i=0;i<10;i++)session.accept({x:45+i*2,y:61,t:performance.now()+i,pointerType:'mouse'});await session.end();return window.__rt.compare();},blend);r.checks.push({name:'blend-'+blend,...v});if(v.channelsOver3)r.pixelDifferences=(r.pixelDifferences??[]).concat({blend,...v});}
 // Visible canvas comparison before any formal deposits: low-flow density must survive refinement.
 for(const index of [0,1,4,7,13,16,24,27,39,49]){v=await page.evaluate(async index=>{const {session,renderer,presets}=window.__rt;session.records=[];await session.rebuild();renderer.confirmDelay=Infinity;session.prediction=false;session.begin({...presets[index],size:20,stabilization:0});const t=performance.now();for(let i=0;i<48;i++)session.accept({x:40+i,y:80+Math.sin(i/12)*3,t:t+i*1000/240,pressure:.7,pointerType:'pen',tilt:.3,azimuth:.4,twist:.5});await session.end();const revision=renderer.mailbox.revision,deadline=performance.now()+30000;while(!renderer.completions.some(m=>m.revision>=revision)){if(performance.now()>deadline)throw Error('latest live snapshot completion timeout');await new Promise(r=>requestAnimationFrame(r));}const result=await window.__rt.compareLive();renderer.confirmDelay=0;return result;},index);r.checks.push({name:'live-before-confirmed-'+index,...v});await checkpoint();if(v.channelsOver3)r.previewDifferences=(r.previewDifferences??[]).concat({index,...v});}
 // More than four ended strokes remain visible while formal rendering is deliberately blocked.
 v=await page.evaluate(async()=>{const {session,renderer,presets}=window.__rt;session.records=[];await session.rebuild();renderer.confirmDelay=Infinity;session.prediction=true;const wait=async revision=>{const deadline=performance.now()+30000;while(!renderer.completions.some(m=>m.revision>=revision)){if(performance.now()>deadline)throw Error('feedback archive completion timeout');await new Promise(r=>requestAnimationFrame(r));}};for(let stroke=0;stroke<12;stroke++){session.begin({...presets[4],size:20,opacity:.4,stabilization:0,color:[stroke/11,.2,.7]});const t=performance.now();for(let i=0;i<8;i++)session.accept({x:42+i*3,y:120+stroke%3*5,t:t+i,pointerType:'mouse'});session.predictions([{x:68,y:120+stroke%3*5,t:t+15,pointerType:'mouse'}]);session.updateLive(performance.now());await wait(renderer.mailbox.revision);await session.end();}await wait(renderer.mailbox.revision);const result={...await window.__rt.compareLive(),records:session.records.length,rawSamples:session.records.reduce((n,r)=>n+r.raw.length,0),formalJobsStillWaiting:renderer.document.jobs.length,archivedThrough:renderer.backend.archivedThrough};renderer.confirmDelay=0;return result;});r.checks.push({name:'feedback-archive-with-formal-stall',...v});assert.equal(v.records,12);assert.equal(v.rawSamples,96);assert.ok(v.formalJobsStillWaiting>0);if(v.channelsOver3)r.previewDifferences=(r.previewDifferences??[]).concat({name:'feedback-archive-with-formal-stall',...v});await checkpoint();
 await page.goto(`http://127.0.0.1:${port}/?backend=${backend}&document=2048`);await page.waitForFunction(()=>!!window.__rt);r.benchmarkDimensions=[2048,1536];
 // Same 4-second input at 4 widths and 3 real wall-clock input frequencies.
 for(const size of [16,128,512,1024])for(const hz of [60,120,240]){await page.evaluate(async()=>{window.__rt.session.records=[];await window.__rt.session.rebuild();});const b=await page.evaluate(o=>window.__rt.run(o),{size,hz,duration:4000,shape:'fast-curve',brushIndex:4,prediction:false});r.benchmarks.push(b);if(b.actualSamples!==4*hz)r.inputGeneratorFailures=(r.inputGeneratorFailures??[]).concat({size,hz,samples:b.actualSamples});await checkpoint();assert.equal(await page.evaluate(()=>window.__rt.renderer.errors.length),0);console.log('RT_BENCH:'+JSON.stringify({backend,...Object.fromEntries(Object.entries(b).filter(([k])=>k!=='samplesDetail'))}));}
 // Intentional formal stall: every real sample survives; latest preview remains bounded.
 await page.evaluate(async()=>{window.__rt.session.records=[];await window.__rt.session.rebuild();});r.benchmarks.push(await page.evaluate(()=>window.__rt.run({size:1024,hz:240,duration:5000,shape:'reversal',brushIndex:4,delay:100,prediction:true})));await page.evaluate(()=>window.__rt.renderer.confirmDelay=0);
 if(process.env.RT_LONG_TEST==='1'){await page.evaluate(async()=>{window.__rt.session.records=[];await window.__rt.session.rebuild();});r.benchmarks.push(await page.evaluate(()=>window.__rt.run({size:1024,hz:240,duration:180000,shape:'long',brushIndex:4,prediction:false})));}
 // Full pattern collection is generated through the real worker and GPU.
 for(const shape of ['line','slow-curve','fast-curve','s','small-circle','large-circle','zigzag','reversal','short','long','taper','pressure-step']){await page.evaluate(async()=>{window.__rt.session.records=[];await window.__rt.session.rebuild();});const b=await page.evaluate(o=>window.__rt.run(o),{size:16,hz:240,duration:400,shape,brushIndex:5,prediction:true});r.checks.push({name:'pattern-'+shape,samples:b.actualSamples,errors:await page.evaluate(()=>window.__rt.errors())});}
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(evidence,backend+'-mobile.png'),fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);assert.equal(overflow,false);r.checks.push({name:'mobile-overflow',status:'PASS'});assert.deepEqual(errors,[]);assert.deepEqual(await page.evaluate(()=>window.__rt.errors()),[]);r.latencyDifferences=r.benchmarks.filter(b=>b.duration>=4000&&b.growthGate!=='PASS_PROXY').map(b=>({size:b.size,hz:b.hz,shape:b.shape,duration:b.duration,start:b.startP95,end:b.endP95,growth:b.growth}));if(r.pixelDifferences?.length||r.previewDifferences?.length||r.latencyDifferences?.length||r.inputGeneratorFailures?.length){failed=true;r.status='GATE_FAIL';}else r.status='CHECKS_PASS';r.physicalVisibleTip='UNVERIFIED';
}catch(e){failed=true;r.status='FAIL';r.failure=e.stack?.replace(/data:text\/javascript;base64,[A-Za-z0-9+/=]+/g,'[embedded module]');await page.screenshot({path:path.join(evidence,backend+'-failure.png'),fullPage:true}).catch(()=>{});console.error(backend,r.failure,JSON.stringify({errors,status:r.message,info:r.info}));}finally{r.consoleErrors=errors;await fs.writeFile(path.join(evidence,'browser-results.json'),JSON.stringify(report,null,2));await page.close();}}}finally{await browser.close();server.close();await fs.writeFile(path.join(evidence,'browser-results.json'),JSON.stringify(report,null,2));}
console.log('RT_RESULT:'+JSON.stringify({...report,backends:report.backends.map(r=>({...r,benchmarks:r.benchmarks.map(({samplesDetail,...b})=>b)}))}));if(failed)process.exitCode=1;
